// Qwen3.8-27B tokenizer parity against HuggingFace.
//
// Same contract as test_tokenizer_compat.cpp, different tokenizer: Qwen3.8
// ships a 248k-entry BPE (248044 vocab entries, 248077 with added tokens),
// where the Qwen3 family that test covers is 151k. One golden cannot serve
// both, so this one carries its own — generated by the same script:
//
//   docker run --rm -v $HOME/models:/models:ro -v $PWD:/src --user $(id -u):$(id -g) \
//     <a container with transformers> \
//     python3 /src/tests/refs/gen_tokenizer_golden.py /models/Qwen3.8-27B \
//     /src/tests/refs/tokenizer_golden_qwen38.h tokenizer_golden_qwen38
//
// It reads only tokenizer.json (Tokenizer::load takes a standalone file), so
// it needs no weights, no GPU and no model load — 11 MB of JSON, not 20 GB.
//
// The comparison is byte-exact in BOTH directions: the ids HF produced, and
// the string HF decoded them back to. A test that only compared ids would pass
// on a tokenizer that encodes correctly and detokenizes wrong, which is the
// half a user actually reads.

#include "model/tokenizer.h"
#include "refs/tokenizer_golden_qwen38.h"
#include "test_models.h"

#include <gtest/gtest.h>
#include <cstdlib>
#include <filesystem>
#include <string>
#include <vector>

namespace {

// Set to the Qwen3.8 model DIRECTORY (any of the BF16/FP8/NVFP4 exports — they
// all ship the same tokenizer.json) or straight to a tokenizer.json.
constexpr const char* kEnvQwen38 = "IMP_TEST_MODEL_QWEN38";

std::string ids_to_string(const std::vector<int32_t>& ids) {
    std::string s;
    for (size_t i = 0; i < ids.size(); i++) {
        if (i)
            s += ' ';
        s += std::to_string(ids[i]);
    }
    return s;
}

class Qwen38TokenizerParityTest : public ::testing::Test {
protected:
    void SetUp() override {
        const char* env = std::getenv(kEnvQwen38);
        if (!env) {
            GTEST_SKIP() << "Set " << kEnvQwen38 << " to a Qwen3.8 model directory (or its "
                         << "tokenizer.json) to run; the golden is "
                         << tokenizer_golden_qwen38::k_model;
        }
        // A set-but-wrong path must FAIL, not skip. A silent skip on a typo is
        // how whole batteries in this repo went missing for weeks.
        std::filesystem::path p(env);
        if (std::filesystem::is_directory(p))
            p /= "tokenizer.json";
        ASSERT_TRUE(std::filesystem::exists(p))
            << kEnvQwen38 << " is set to \"" << env << "\" but " << p.string() << " does not exist";
        ASSERT_TRUE(tok_.load(p.string())) << "Tokenizer::load failed for " << p.string();
        json_path_ = p.string();
    }

    // HF's add_special_tokens=False. imp prepends BOS when the model asks for
    // it; drop that one token rather than the whole comparison.
    std::vector<int32_t> encode_like_hf(const std::string& text) {
        auto ids = tok_.encode(text, /*no_prefix=*/false);
        if (!ids.empty() && ids[0] == tok_.bos_id() && tok_.add_bos())
            ids.erase(ids.begin());
        return ids;
    }

    imp::Tokenizer tok_;
    std::string json_path_;
};

TEST_F(Qwen38TokenizerParityTest, FingerprintIdentifiesTheTokenizer) {
    // Comparing against the wrong tokenizer's golden would report mismatches
    // that say nothing about imp. Fail loudly here instead, because unlike the
    // Qwen3 test this one is pointed at an explicitly named model.
    auto fp = encode_like_hf(tokenizer_golden_qwen38::k_fingerprint_text);
    EXPECT_EQ(fp, tokenizer_golden_qwen38::k_fingerprint_ids)
        << json_path_ << " is not the tokenizer this golden describes ("
        << tokenizer_golden_qwen38::k_model << ")";
}

TEST_F(Qwen38TokenizerParityTest, EncodeMatchesHuggingFaceOnEveryCase) {
    int mismatches = 0;
    for (const auto& c : tokenizer_golden_qwen38::cases()) {
        auto ids = encode_like_hf(c.text);
        if (ids != c.ids) {
            mismatches++;
            ADD_FAILURE() << "encode mismatch for \"" << c.text << "\"\n"
                          << "  imp: [" << ids_to_string(ids) << "]\n"
                          << "  HF : [" << ids_to_string(c.ids) << "]";
        }
    }
    EXPECT_EQ(mismatches, 0) << mismatches << " of " << tokenizer_golden_qwen38::cases().size()
                             << " cases differ from the HF reference";
}

TEST_F(Qwen38TokenizerParityTest, RoundTripIsByteIdentical) {
    // encode -> decode must return what HF returned for the same ids. This is
    // the half that catches a detokenizer that drops a space run or mangles a
    // multi-byte sequence while the ids were right.
    for (const auto& c : tokenizer_golden_qwen38::cases()) {
        auto ids = encode_like_hf(c.text);
        const std::string decoded = tok_.decode(ids);
        EXPECT_EQ(decoded, std::string(c.decoded))
            << "decode mismatch for \"" << c.text << "\" (ids [" << ids_to_string(ids) << "])";
    }
}

TEST_F(Qwen38TokenizerParityTest, VocabSizeMatchesTheCheckpoint) {
    // 248044 base entries + added tokens = 248077. config.json declares
    // vocab_size 248320: the embedding matrix is padded past the tokenizer, so
    // these three numbers are SUPPOSED to differ. Asserting the two the
    // tokenizer owns keeps a truncated vocab from passing as "close enough".
    EXPECT_EQ(tok_.vocab_size(), tokenizer_golden_qwen38::k_n_tokens);
}

}  // namespace
