#include <gtest/gtest.h>
#include "model/tokenizer.h"
#include "model/gguf_loader.h"
#include "core/logging.h"

#include <fstream>
#include <string>
#include <vector>

// Minimal JSON parsing for the golden file

namespace {

// Simple JSON array-of-int parser for the "ids" field
std::vector<int32_t> parse_int_array(const std::string& json, const std::string& key) {
    std::vector<int32_t> result;
    size_t pos = json.find("\"" + key + "\"");
    if (pos == std::string::npos)
        return result;
    pos = json.find('[', pos);
    if (pos == std::string::npos)
        return result;
    pos++;  // skip '['
    while (pos < json.size()) {
        while (pos < json.size() && (json[pos] == ' ' || json[pos] == '\n' || json[pos] == ','))
            pos++;
        if (pos >= json.size() || json[pos] == ']')
            break;
        int sign = 1;
        if (json[pos] == '-') {
            sign = -1;
            pos++;
        }
        int32_t val = 0;
        while (pos < json.size() && json[pos] >= '0' && json[pos] <= '9') {
            val = val * 10 + (json[pos] - '0');
            pos++;
        }
        result.push_back(val * sign);
    }
    return result;
}

std::string parse_string(const std::string& json, const std::string& key) {
    size_t pos = json.find("\"" + key + "\"");
    if (pos == std::string::npos)
        return "";
    pos = json.find(':', pos);
    if (pos == std::string::npos)
        return "";
    pos = json.find('"', pos + 1);
    if (pos == std::string::npos)
        return "";
    pos++;  // skip opening quote
    std::string result;
    while (pos < json.size() && json[pos] != '"') {
        if (json[pos] == '\\' && pos + 1 < json.size()) {
            pos++;
            switch (json[pos]) {
                case 'n':
                    result += '\n';
                    break;
                case 't':
                    result += '\t';
                    break;
                case '"':
                    result += '"';
                    break;
                case '\\':
                    result += '\\';
                    break;
                default:
                    result += json[pos];
                    break;
            }
        } else {
            result += json[pos];
        }
        pos++;
    }
    return result;
}

}  // namespace

class TokenizerCompatTest : public ::testing::Test {
protected:
    void SetUp() override {
        // This test requires:
        // 1. A GGUF model loaded (provides tokenizer)
        // 2. A golden JSON file generated by generate_tokenizer_golden.py
        // Both are optional — test is skipped if not available.

        const char* model_env = std::getenv("IMP_TEST_MODEL");
        const char* golden_env = std::getenv("IMP_TEST_GOLDEN");

        if (!model_env || !golden_env) {
            GTEST_SKIP() << "Set IMP_TEST_MODEL and IMP_TEST_GOLDEN env vars to run";
        }

        model_path_ = model_env;
        golden_path_ = golden_env;
    }

    std::string model_path_;
    std::string golden_path_;
};

TEST_F(TokenizerCompatTest, MatchesHuggingFace) {
    // Load model (for tokenizer)
    auto model = imp::load_gguf(model_path_);
    ASSERT_NE(model, nullptr) << "Failed to load model: " << model_path_;

    auto* tok = model->tokenizer();
    ASSERT_NE(tok, nullptr) << "Model has no tokenizer";

    // Load golden file
    std::ifstream f(golden_path_);
    ASSERT_TRUE(f.is_open()) << "Failed to open golden file: " << golden_path_;
    std::string golden_json((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());

    // Parse test cases (crude but functional JSON parsing)
    // Split by "text" keys to find individual cases
    size_t pos = 0;
    int n_match = 0, n_mismatch = 0, n_total = 0;

    while ((pos = golden_json.find("\"text\"", pos)) != std::string::npos) {
        // Find the enclosing object
        size_t obj_start = golden_json.rfind('{', pos);
        size_t obj_end = golden_json.find('}', pos);
        if (obj_start == std::string::npos || obj_end == std::string::npos)
            break;

        std::string case_json = golden_json.substr(obj_start, obj_end - obj_start + 1);

        std::string text = parse_string(case_json, "text");
        std::vector<int32_t> expected_ids = parse_int_array(case_json, "ids");

        // Encode with imp tokenizer (no BOS, matching HF add_special_tokens=False)
        auto actual_ids = tok->encode(text, /*no_prefix=*/false);
        // Remove BOS if present (HF golden uses add_special_tokens=False)
        if (!actual_ids.empty() && actual_ids[0] == tok->bos_id() && tok->add_bos()) {
            actual_ids.erase(actual_ids.begin());
        }

        n_total++;
        if (actual_ids == expected_ids) {
            n_match++;
        } else {
            n_mismatch++;
            // Only log first few mismatches to avoid flooding
            if (n_mismatch <= 5) {
                std::string exp_str, act_str;
                for (int id : expected_ids)
                    exp_str += std::to_string(id) + " ";
                for (int id : actual_ids)
                    act_str += std::to_string(id) + " ";
                ADD_FAILURE() << "Mismatch for text: \"" << text << "\"\n"
                              << "  Expected: " << exp_str << "\n"
                              << "  Actual:   " << act_str;
            }
        }

        pos = obj_end + 1;
    }

    float match_rate = n_total > 0 ? 100.0f * n_match / n_total : 0.0f;
    printf("Tokenizer compat: %d/%d match (%.1f%%)\n", n_match, n_total, match_rate);

    // We want at least 80% match rate
    EXPECT_GE(match_rate, 80.0f) << "Too many tokenizer mismatches";
}
