// Tokenizer parity against HuggingFace transformers.
//
// The golden is a committed header (tests/refs/tokenizer_golden_qwen3.h),
// generated by tests/refs/gen_tokenizer_golden.py. Two things it replaces:
//
//   - IMP_TEST_GOLDEN. No golden file was ever committed and nothing in the
//     repo set the variable, so this test skipped on every run there has
//     ever been (#1569). A header cannot go missing without the build
//     failing.
//   - the hand-written JSON scan. It cut each case at the first '}' after
//     "text", which truncated the one case containing a '}' inside a string
//     ("JSON: {\"key\": ...}") and compared imp's 15 ids against an empty
//     expectation - one of twenty cases permanently unverifiable (#1570).
//
// What still gates the run is IMP_TEST_MODEL: imp's tokenizer comes out of a
// GGUF, and CI has no model. `make test-gpu` sets it.

#include <gtest/gtest.h>
#include "model/tokenizer.h"
#include "model/gguf_loader.h"
#include "core/logging.h"
#include "test_models.h"
#include "refs/tokenizer_golden_qwen3.h"

#include <string>
#include <vector>

namespace {

std::string ids_to_string(const std::vector<int32_t>& ids) {
    std::string s;
    for (size_t i = 0; i < ids.size(); i++) {
        if (i)
            s += ' ';
        s += std::to_string(ids[i]);
    }
    return s;
}

}  // namespace

class TokenizerCompatTest : public ::testing::Test {
protected:
    void SetUp() override {
        const char* model_env = std::getenv(imp_test::kEnvModel);
        if (!model_env) {
            GTEST_SKIP() << "Set " << imp_test::kEnvModel << " to a Qwen3 GGUF to run "
                         << "(the golden is " << tokenizer_golden::k_model << "; `make test-gpu` "
                         << "sets the variable)";
        }
        ASSERT_NO_FATAL_FAILURE(imp_test::require_readable(model_env, imp_test::kEnvModel));
        model_path_ = model_env;
    }

    std::string model_path_;
};

TEST_F(TokenizerCompatTest, MatchesHuggingFace) {
    auto model = imp::load_gguf(model_path_);
    ASSERT_NE(model, nullptr) << "Failed to load model: " << model_path_;

    auto* tok = model->tokenizer();
    ASSERT_NE(tok, nullptr) << "Model has no tokenizer";

    // HF's add_special_tokens=False. imp prepends BOS when the model asks for
    // it, so drop that one token rather than the whole comparison.
    auto encode_like_hf = [&](const std::string& text) {
        auto ids = tok->encode(text, /*no_prefix=*/false);
        if (!ids.empty() && ids[0] == tok->bos_id() && tok->add_bos())
            ids.erase(ids.begin());
        return ids;
    };

    // A golden for a different tokenizer would report mismatches that say
    // nothing about imp. Skip on the fingerprint instead of failing: pointing
    // IMP_TEST_MODEL at a Llama GGUF is a legitimate thing to do.
    {
        auto fp = encode_like_hf(tokenizer_golden::k_fingerprint_text);
        if (fp != tokenizer_golden::k_fingerprint_ids) {
            GTEST_SKIP() << model_path_ << " is not the tokenizer this golden describes ("
                         << tokenizer_golden::k_model << "): \"" << tokenizer_golden::k_fingerprint_text
                         << "\" encodes to [" << ids_to_string(fp) << "], golden says ["
                         << ids_to_string(tokenizer_golden::k_fingerprint_ids) << "]";
        }
    }

    int n_match = 0;
    const auto& cases = tokenizer_golden::cases();
    ASSERT_FALSE(cases.empty());

    for (const auto& c : cases) {
        const std::string text = c.text;
        auto ids = encode_like_hf(text);
        if (ids == c.ids) {
            n_match++;
        } else {
            ADD_FAILURE() << "encode mismatch for \"" << text << "\"\n"
                          << "  expected: [" << ids_to_string(c.ids) << "]\n"
                          << "  actual:   [" << ids_to_string(ids) << "]";
        }
        // decode was generated all along and asserted nowhere. A tokenizer can
        // encode correctly and reassemble the bytes wrongly - that is exactly
        // the shape of the whitespace-run defect this corpus over-samples.
        EXPECT_EQ(tok->decode(c.ids), std::string(c.decoded)) << "decode mismatch for \"" << text << "\"";
    }

    printf("Tokenizer compat: %d/%zu encode cases match (%s vs golden %s)\n", n_match, cases.size(),
           model_path_.c_str(), tokenizer_golden::k_model);

    // Every case, not a percentage. The old bar was 80% over a 20-case corpus,
    // i.e. "4 of 20 may diverge" - and exactly 4 of those 20 are runs of
    // whitespace, the #657 defect class.
    EXPECT_EQ(n_match, static_cast<int>(cases.size()));
}
