// Attention cross-path agreement — TEST_AUDIT (retired) risk #1.
//
// The engine has SIX prefill-attention implementations that MUST agree:
// cuBLAS materialized, WMMA FMHA (fmha_sm120), fp8 FMHA, FA2 (e4m3 QK),
// FA2 (f16 QK), and flash_attention_blackwell. The #493 regression shipped
// because nothing asserted cross-path agreement under realistic data — every
// per-kernel parity test was green on benign fills.
//
// Ground truth: an fp64 CPU reference computed from the f16-rounded inputs.
// The reference itself is verified against a committed numpy fp64 golden
// (tests/refs/attention_crosspath_golden.h, 64 spot values per config,
// 1e-9 rel) — proving the in-test reference and the independent generator
// compute the same math. Inputs are heavy-tailed realistic magnitudes
// (cubed-uniform, amp 8, 1/256 outliers to ~±64 — QK-normed model regime),
// generated by an integer LCG with f32 multiply-only transforms so numpy
// and C++ produce bit-identical f16 bits (no libm divergence).
//
// Tolerances (tests/refs/README.md):
//   f16-class (cuBLAS, WMMA, FA2-f16, blackwell): 1e-2 rel vs fp64 ref
//   fp8-class (fp8 FMHA, FA2-e4m3): 5e-2 rel vs fp64 ref (e4m3 score noise)
//   pairwise f16-class agreement: 1e-2 (the killer assert)

#include <gtest/gtest.h>
#include "compute/attention_cublas.h"
#include "compute/attention_fmha_sm120.h"
#include "compute/attention_tc.h"
#include "core/tensor.h"
#include "refs/attention_crosspath_golden.h"
#include "runtime/process_diag.h"
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

namespace imp {
namespace {

// Bit-exact mirror of tests/refs/gen_attention_crosspath_golden.py::lcg_fill.
void lcg_fill(std::vector<half>& out, uint32_t seed, float amp) {
    uint32_t x = seed;
    for (auto& h : out) {
        x = x * 1664525u + 1013904223u;
        int32_t v = (int32_t)((x >> 8) & 0x3FFFu) - 8192;
        float f = (float)v * (1.0f / 8192.0f);
        float val = f * f * f * amp;
        if ((x & 0xFFu) == 0)
            val *= 2.0f;  // 1/256 outliers to ~±16 (observed QK-normed spikes ~±10)
        h = __float2half(val);
    }
}

// fp64 reference from the f16-rounded inputs (same math as the generator).
void ref_attention_f64(const std::vector<half>& Qh, const std::vector<half>& Kh,
                       const std::vector<half>& Vh, std::vector<double>& O, int Sq, int Skv, int NH,
                       int NKV, int HD, bool causal, int sw, double softcap) {
    const double scale = 1.0 / std::sqrt((double)HD);
    const int gqa = NH / NKV;
    O.assign((size_t)Sq * NH * HD, 0.0);
    std::vector<double> S(Skv);
    for (int h = 0; h < NH; h++) {
        int kvh = h / gqa;
        for (int i = 0; i < Sq; i++) {
            double m = -1e300;
            for (int j = 0; j < Skv; j++) {
                double dot = 0.0;
                for (int d = 0; d < HD; d++) {
                    dot += (double)__half2float(Qh[((size_t)i * NH + h) * HD + d]) *
                           (double)__half2float(Kh[((size_t)j * NKV + kvh) * HD + d]);
                }
                dot *= scale;
                if (softcap > 0.0)
                    dot = softcap * std::tanh(dot / softcap);
                if ((causal && j > i) || (sw > 0 && (i - j) >= sw))
                    dot = -1e300;
                S[j] = dot;
                m = std::max(m, dot);
            }
            double l = 0.0;
            for (int j = 0; j < Skv; j++) {
                S[j] = (S[j] <= -1e299) ? 0.0 : std::exp(S[j] - m);
                l += S[j];
            }
            for (int d = 0; d < HD; d++) {
                double acc = 0.0;
                for (int j = 0; j < Skv; j++)
                    acc += S[j] * (double)__half2float(Vh[((size_t)j * NKV + kvh) * HD + d]);
                O[((size_t)i * NH + h) * HD + d] = acc / l;
            }
        }
    }
}

struct PathResult {
    std::string name;
    bool fp8_class = false;
    bool ran = false;
    std::vector<float> O;
};

struct ErrStats {
    float max_rel = 0.0f;
    float p999 = 0.0f;  // 99.9th percentile of rel error
    int above_tol = 0;  // elements exceeding the path tolerance
    int nan_count = 0;

    std::string str() const {
        char buf[128];
        snprintf(buf, sizeof(buf), "max_rel=%g p99.9=%g above_tol=%d nan=%d", max_rel, p999, above_tol,
                 nan_count);
        return buf;
    }
};

ErrStats err_stats(const std::vector<float>& got, const std::vector<double>& ref, float tol) {
    ErrStats s;
    std::vector<float> errs;
    errs.reserve(got.size());
    for (size_t i = 0; i < got.size(); i++) {
        if (std::isnan(got[i])) {
            s.nan_count++;
            continue;
        }
        double denom = std::max(1.0, std::fabs(ref[i]));
        float e = (float)(std::fabs((double)got[i] - ref[i]) / denom);
        errs.push_back(e);
        s.max_rel = std::max(s.max_rel, e);
        if (e > tol)
            s.above_tol++;
    }
    if (!errs.empty()) {
        size_t k = (size_t)((double)(errs.size() - 1) * 0.999);
        std::nth_element(errs.begin(), errs.begin() + k, errs.end());
        s.p999 = errs[k];
    }
    return s;
}

class AttentionCrossPathTest : public ::testing::Test {
protected:
    void SetUp() override {
        cudaStreamCreate(&stream_);
        // The strictness model below assumes FA2-f16 runs the f32-score-chain
        // variant. Pin it explicitly — the process_diag defaults follow the
        // production config (f16acc on since #674), which only meets the wider
        // f16-class envelope, not the 1e-2 pairwise assert.
        saved_f16acc_ = imp::process_diag_fa2_f16acc();
        saved_pv_f16acc_ = imp::process_diag_fa2_pv_f16acc();
        imp::process_diag_set_fa2_f16acc(false);
        imp::process_diag_set_fa2_pv_f16acc(false);
    }
    void TearDown() override {
        imp::process_diag_set_fa2_f16acc(saved_f16acc_);
        imp::process_diag_set_fa2_pv_f16acc(saved_pv_f16acc_);
        cudaStreamDestroy(stream_);
    }
    bool saved_f16acc_ = false;
    bool saved_pv_f16acc_ = false;

    // Strictness model (see tests/refs/README.md):
    // the f32-score-chain paths (cuBLAS FP32-S, FA2-f16) and — since the
    // #528 fix (in-place float→half S/P-tile compaction raced across rows;
    // post-fix ~4e-4 max_rel) — the WMMA paths (fmha_sm120, blackwell)
    // reproduce the fp64 reference at 1e-2 on realistic uncorrelated data.
    // All four are held strict in BOTH tiers; the f32 pair additionally has
    // pairwise agreement. The fp8-QK paths (score-quantization noise, worst
    // at short rows where no averaging happens — the #512 mechanism) are
    // CHARACTERIZED: stats printed, only gross breakage (NaN, envelope
    // exceeded) fails. mild=true selects the tighter envelope.
    void run_config(int cfg_idx, const char* name, int Sq, int Skv, int NH, int NKV, int HD, bool causal,
                    int sw, float softcap, float amp, bool mild, const int* spot_idx,
                    const double* spot_val, int n_spots) {
        SCOPED_TRACE(name);
        const float scale = 1.0f / std::sqrt((float)HD);
        const size_t q_elems = (size_t)Sq * NH * HD;
        const size_t kv_elems = (size_t)Skv * NKV * HD;

        std::vector<half> Qh(q_elems), Kh(kv_elems), Vh(kv_elems);
        lcg_fill(Qh, 0x1234u + cfg_idx * 3, amp);
        lcg_fill(Kh, 0x5678u + cfg_idx * 3, amp);
        lcg_fill(Vh, 0x9ABCu + cfg_idx * 3, 1.0f);  // V is not QK-normed

        // ---- fp64 reference + generator-parity spot check (1e-9 rel) ----
        std::vector<double> ref;
        ref_attention_f64(Qh, Kh, Vh, ref, Sq, Skv, NH, NKV, HD, causal, sw, softcap);
        for (int k = 0; k < n_spots; k++) {
            double got = ref[spot_idx[k]], want = spot_val[k];
            double denom = std::max(1.0, std::fabs(want));
            ASSERT_LT(std::fabs(got - want) / denom, 1e-9)
                << "in-test fp64 reference diverges from the committed numpy golden at spot " << k
                << " (idx " << spot_idx[k] << "): got " << got << " want " << want
                << " — generator and test no longer compute the same math";
        }

        // ---- device buffers ----
        void *d_q, *d_k, *d_v, *d_o, *d_s;
        const size_t s_elems = (size_t)2 * NH * Sq * Skv;  // 2x: forces the production FP32-S path
        ASSERT_EQ(cudaMalloc(&d_q, q_elems * 2), cudaSuccess);
        ASSERT_EQ(cudaMalloc(&d_k, kv_elems * 2), cudaSuccess);
        ASSERT_EQ(cudaMalloc(&d_v, kv_elems * 2), cudaSuccess);
        ASSERT_EQ(cudaMalloc(&d_o, q_elems * 2), cudaSuccess);
        ASSERT_EQ(cudaMalloc(&d_s, s_elems * 2), cudaSuccess);
        cudaMemcpy(d_q, Qh.data(), q_elems * 2, cudaMemcpyHostToDevice);
        cudaMemcpy(d_k, Kh.data(), kv_elems * 2, cudaMemcpyHostToDevice);
        cudaMemcpy(d_v, Vh.data(), kv_elems * 2, cudaMemcpyHostToDevice);

        int64_t q2[2] = {Sq, (int64_t)NH * HD};
        int64_t kv2[2] = {Skv, (int64_t)NKV * HD};
        int64_t s3[3] = {NH, Sq, 2 * (int64_t)Skv};
        int64_t q4[4] = {1, Sq, NH, HD};
        int64_t kv4[4] = {1, Skv, NKV, HD};
        Tensor Q2(d_q, QType::F16, 2, q2, true), K2(d_k, QType::F16, 2, kv2, true);
        Tensor V2(d_v, QType::F16, 2, kv2, true), O2(d_o, QType::F16, 2, q2, true);
        Tensor S3(d_s, QType::F16, 3, s3, true);
        Tensor Q4(d_q, QType::F16, 4, q4, true), K4(d_k, QType::F16, 4, kv4, true);
        Tensor V4(d_v, QType::F16, 4, kv4, true), O4(d_o, QType::F16, 4, q4, true);

        auto collect = [&](PathResult& r) {
            cudaStreamSynchronize(stream_);
            ASSERT_EQ(cudaGetLastError(), cudaSuccess) << r.name;
            std::vector<half> h(q_elems);
            cudaMemcpy(h.data(), d_o, q_elems * 2, cudaMemcpyDeviceToHost);
            r.O.resize(q_elems);
            for (size_t i = 0; i < q_elems; i++)
                r.O[i] = __half2float(h[i]);
        };
        auto clear_o = [&] { cudaMemset(d_o, 0, q_elems * 2); };

        std::vector<PathResult> results;

        {  // 1. cuBLAS materialized (the executor's historic short-prefill reference)
            PathResult r{"cublas"};
            clear_o();
            attention_cublas_prefill(Q2, K2, V2, O2, S3, NH, NKV, HD, scale, causal, softcap, 0, stream_,
                                     sw);
            r.ran = true;
            collect(r);
            results.push_back(std::move(r));
        }
        {  // 2. WMMA FMHA (fmha_sm120)
            PathResult r{"fmha_sm120_f16"};
            clear_o();
            r.ran = fmha_sm120_prefill(Q4, K4, V4, O4, scale, causal, sw, softcap, stream_);
            if (r.ran)
                collect(r);
            results.push_back(std::move(r));
        }
        {  // 3. fp8 FMHA (smem-materializing)
            PathResult r{"fmha_fp8", /*fp8_class=*/true};
            clear_o();
            r.ran = fmha_sm120_fp8_prefill(Q4, K4, V4, O4, scale, causal, sw, softcap, stream_);
            if (r.ran)
                collect(r);
            results.push_back(std::move(r));
        }
        {  // 4. FA2 register-resident, e4m3 QK
            PathResult r{"fa2_e4m3", /*fp8_class=*/true};
            clear_o();
            r.ran = fmha_sm120_fa2_prefill(Q4, K4, V4, O4, scale, causal, sw, softcap, stream_, 0, false);
            if (r.ran)
                collect(r);
            results.push_back(std::move(r));
        }
        {  // 5. FA2 register-resident, f16 QK (the short-prefill production path, #525)
            PathResult r{"fa2_f16"};
            clear_o();
            r.ran = fmha_sm120_fa2_prefill(Q4, K4, V4, O4, scale, causal, sw, softcap, stream_, 0, true);
            if (r.ran)
                collect(r);
            results.push_back(std::move(r));
        }
        {  // 6. flash_attention_blackwell (the dispatcher's final tier)
            PathResult r{"blackwell"};
            clear_o();
            r.ran = flash_attention_blackwell(Q4, K4, V4, O4, scale, causal, sw, softcap, stream_, 0);
            if (r.ran)
                collect(r);
            results.push_back(std::move(r));
        }

        cudaFree(d_q);
        cudaFree(d_k);
        cudaFree(d_v);
        cudaFree(d_o);
        cudaFree(d_s);

        // hd=128 is the production hot shape: the register-resident paths must
        // not silently decline (a perf rewrite that stops running is a bug).
        // Gated on Sq>=16: a 1-/2-token prefill is legitimately routed through
        // the decode path, so the prefill FA2 kernels MAY decline there — we
        // still check correctness of whatever paths do run (below).
        for (auto& r : results)
            if (HD == 128 && Sq >= 16 &&
                (r.name == "fa2_e4m3" || r.name == "fa2_f16" || r.name == "fmha_sm120_f16"))
                EXPECT_TRUE(r.ran) << r.name << " declined hd=128 config " << name;

        // f32-score-chain paths: exact-ish QK accumulation + f32 softmax —
        // these track the fp64 reference even on sharp data.
        auto f32_chain = [](const PathResult& r) { return r.name == "cublas" || r.name == "fa2_f16"; };
        // f16-class strict: f16 QK with f32 accumulators + f32 softmax + f16 P.
        // Held to 1e-2 vs fp64 since the #528 race fix (measured ~4e-4).
        auto f16_strict = [&](const PathResult& r) {
            return f32_chain(r) || r.name == "fmha_sm120_f16" || r.name == "blackwell";
        };

        // ---- each path vs the verified fp64 reference ----
        for (auto& r : results) {
            if (!r.ran)
                continue;
            const bool strict = f16_strict(r);
            const float tol = strict ? 1e-2f : (mild ? 1.5f : 4.0f);
            ErrStats e = err_stats(r.O, ref, strict ? tol : 1e-2f);
            EXPECT_EQ(e.nan_count, 0) << r.name << ": NaN in output";
            if (strict) {
                EXPECT_LT(e.max_rel, tol) << r.name << " vs fp64 ref: " << e.str();
                if (e.max_rel >= tol) {  // structural diagnosis: where are the errors?
                    int shown = 0;
                    for (size_t i = 0; i < r.O.size() && shown < 8; i++) {
                        double denom = std::max(1.0, std::fabs(ref[i]));
                        if (std::fabs((double)r.O[i] - ref[i]) / denom > tol * 4) {
                            printf("[crosspath] %s/%s mism @(sq=%zu h=%zu d=%zu) got=%g ref=%g\n", name,
                                   r.name.c_str(), i / ((size_t)NH * HD), (i / HD) % NH, i % HD,
                                   r.O[i], ref[i]);
                            shown++;
                        }
                    }
                }
            } else {
                // characterization: bounded-garbage guard; the printed stats
                // (vs a 1e-2 counting threshold) document the path's measured
                // precision envelope without blessing it as "within tolerance".
                EXPECT_LT(e.max_rel, tol) << r.name << " grossly broken: " << e.str();
                printf("[crosspath] %s/%s (characterized): %s\n", name, r.name.c_str(), e.str().c_str());
            }
        }

        // ---- pairwise agreement of the f32-chain pair (the killer assert:
        // the executor's short-prefill replacement (#525) must be
        // output-equivalent to the materialized cuBLAS path it replaced) ----
        for (size_t a = 0; a < results.size(); a++) {
            if (!results[a].ran || !f32_chain(results[a]))
                continue;
            for (size_t b = a + 1; b < results.size(); b++) {
                if (!results[b].ran || !f32_chain(results[b]))
                    continue;
                std::vector<double> bd(results[b].O.begin(), results[b].O.end());
                ErrStats e = err_stats(results[a].O, bd, 1e-2f);
                // denom here is |b| not |ref| — fine, both are O(1)-bounded outputs
                EXPECT_LT(e.max_rel, 1e-2f)
                    << "paths disagree: " << results[a].name << " vs " << results[b].name << ": "
                    << e.str();
            }
        }
    }

    cudaStream_t stream_ = nullptr;
};

// Configs mirror tests/refs/gen_attention_crosspath_golden.py::CONFIGS exactly.
//
// Measured envelopes on first run (2026-06-04, the suite's birth certificate;
// all numbers = max_rel vs fp64 ref, denom max(1,|ref|)):
//   mild (amp=2, score sigma ~0.6):  fp8-QK 0.58-0.71 (worst at SHORT rows —
//     e4m3 score noise with no averaging, the #512 mechanism), WMMA paths
//     0.15-0.86 DESPITE f32 accumulators (worst at short rows). f32-chain:
//     < 1e-2.
//   sharp (amp=8, near-one-hot softmax): fp8 ~2.3 (76% of elements past
//     5e-2), WMMA ~1.0-1.2. f32-chain still < 1e-2.
// RESOLVED 2026-06-05 (#528): the WMMA divergence was the in-place
// float→half S/P-tile compaction clobbering neighbor rows' float scores
// (half row r aliases the bytes of float row r/2; padding rows raced ahead
// zero-filling valid rows — hence worst at short seq). Post-fix the WMMA
// paths measure ~4e-4 on all four configs and are held strict at 1e-2.
// Production survives the characterized paths because real activations are
// correlated and long-context averaging dilutes per-row flips (#511) — but
// SHORT prefill must stay on the f32 chain (#512, #525), and the old %13
// test fills (periodic + size_t-underflow-poisoned) could never see any of
// this.
TEST_F(AttentionCrossPathTest, MildLongGQA) {
    run_config(0, "mild_long_gqa", 192, 192, 4, 2, 128, true, 0, 0.0f, 2.0f, /*mild=*/true,
               imp_refs::mild_long_gqa_spot_idx, imp_refs::mild_long_gqa_spot_val, 64);
}

TEST_F(AttentionCrossPathTest, MildShortGQA32_8) {
    run_config(1, "mild_short_gqa32", 24, 24, 32, 8, 128, true, 0, 0.0f, 2.0f, /*mild=*/true,
               imp_refs::mild_short_gqa32_spot_idx, imp_refs::mild_short_gqa32_spot_val, 64);
}

TEST_F(AttentionCrossPathTest, MildSlidingWindowSoftcap) {
    run_config(2, "mild_sliding_softcap", 160, 160, 4, 4, 128, true, 64, 50.0f, 2.0f, /*mild=*/true,
               imp_refs::mild_sliding_softcap_spot_idx, imp_refs::mild_sliding_softcap_spot_val, 64);
}

TEST_F(AttentionCrossPathTest, SharpLongGQA_F32ChainStrict) {
    run_config(3, "sharp_long_gqa", 192, 192, 4, 2, 128, true, 0, 0.0f, 8.0f, /*mild=*/false,
               imp_refs::sharp_long_gqa_spot_idx, imp_refs::sharp_long_gqa_spot_val, 64);
}

// Regression for the FP32-S softcap drop (Gemma-2 attn_logit_softcap=50).
// The mild softcap config above keeps scores << 50, so tanh(s/50)*50 ≈ s and a
// dropped softcap is invisible. Here softcap=2 with amp=8 SATURATES the cap
// (|score| >> 2 → tanh(s/2)*2 → ±2), so the cuBLAS FP32-S path (and the
// pairwise-equal fa2_f16 path, which applies softcap) MUST cap or they diverge
// from the capped fp64 reference. No committed golden spots (n_spots=0): the
// in-test fp64 ref IS ground truth here. Covers both the MHA and GQA softcap
// launch sites in attention_cublas_prefill. Was RED before the FP32-S softcap
// kernel was added (softcap was gated behind !use_fp32_s).
TEST_F(AttentionCrossPathTest, SaturatingSoftcap_FP32S_MHA) {
    run_config(4, "saturating_softcap_mha", 64, 64, 4, 4, 128, true, 0, /*softcap=*/2.0f, 8.0f,
               /*mild=*/false, nullptr, nullptr, 0);
}

TEST_F(AttentionCrossPathTest, SaturatingSoftcap_FP32S_GQA) {
    run_config(5, "saturating_softcap_gqa", 64, 64, 8, 2, 128, true, 0, /*softcap=*/2.0f, 8.0f,
               /*mild=*/false, nullptr, nullptr, 0);
}

// ---- seqlen edge cases (TEST_AUDIT (retired) §7 Tier-0): the crosspath matrix
// previously bottomed out at Sq=24. These cover the degenerate single-/two-token
// prefill (empty-row / minimal-causal softmax) and the 512-tile boundary +1.
// No committed golden (n_spots=0): the in-test fp64 reference IS ground truth,
// exactly as for the SaturatingSoftcap configs. cfg indices >= 6 keep distinct
// LCG seeds (seed = base + cfg_idx*3) so the data differs per config.
// "max single-pass" (engine max_tokens, ~4096) is deliberately NOT taken
// literally — a 4096x4096 host fp64 reference is too slow for a unit test; 513
// exercises the multi-tile + boundary behavior that the max shape also hits.

TEST_F(AttentionCrossPathTest, SingleTokenPrefill) {
    // Sq=Skv=1: softmax over a single key → O must equal V exactly. The
    // degenerate empty-row case no prefill path tested before.
    run_config(6, "single_token", 1, 1, 4, 2, 128, true, 0, 0.0f, 2.0f, /*mild=*/true, nullptr, nullptr,
               0);
}

TEST_F(AttentionCrossPathTest, TwoTokenCausalPrefill) {
    // Sq=Skv=2 causal: row 0 sees key 0 only; row 1 sees keys 0,1 — the minimal
    // causal mask.
    run_config(7, "two_token_causal", 2, 2, 4, 2, 128, true, 0, 0.0f, 2.0f, /*mild=*/true, nullptr,
               nullptr, 0);
}

TEST_F(AttentionCrossPathTest, TileBoundaryPlusOne_Sq513) {
    // Sq=Skv=513: one full 512-tile plus a 1-row remainder — the ±1-of-tile edge
    // the dispatcher branches on, and a proxy for the largest single-pass shape.
    run_config(8, "tile_boundary_513", 513, 513, 4, 2, 128, true, 0, 0.0f, 2.0f, /*mild=*/true, nullptr,
               nullptr, 0);
}

// ---- head-dim edges (TEST_AUDIT (retired) §7 Tier-1): the parity matrix above is
// HD=128-only. These add cross-path agreement at HD≠128. Whatever production
// path runs at a given HD is held to its class tolerance vs the fp64 ref (the
// "must-not-decline" guard is HD==128-only, so a path that legitimately has no
// HD=64/256 kernel just declines and is skipped). HD=256 is the Gemma-3 #566
// correctness hot-spot; HD=64 a common small-head config. n_spots=0: the in-test
// fp64 ref is ground truth.

TEST_F(AttentionCrossPathTest, HeadDim64) {
    run_config(9, "headdim64", 128, 128, 8, 2, 64, true, 0, 0.0f, 2.0f, /*mild=*/true, nullptr, nullptr,
               0);
}

TEST_F(AttentionCrossPathTest, HeadDim256_Gemma3Hotspot) {
    run_config(10, "headdim256", 128, 128, 4, 2, 256, true, 0, 0.0f, 2.0f, /*mild=*/true, nullptr,
               nullptr, 0);
}

}  // namespace
}  // namespace imp
