// Unicode data for the tokenizer: class bits for the regex pre-tokenizers (\p{L}, \p{M}, \p{N}, \s)
// and NFC. Tables: unicode_class.cpp, unicode_nfc_data.cpp, generated by tools/gen_unicode_tables.py.
#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>

namespace imp::unicode {

enum : uint8_t {
    kUpper = 1,         // Lu, Lt
    kLower = 2,         // Ll
    kOtherLetter = 4,   // Lm, Lo
    kMark = 8,          // Mn, Mc, Me
    kNumber = 16,       // Nd, Nl, No
    kSpace = 32,        // White_Space
    kNfcUnstable = 64,  // NFC may change it: ccc != 0, composes as a second, or NFC(cp) != cp
    kDecimal = 128,     // Nd (regex \d)
    kLetter = kUpper | kLower | kOtherLetter,
};

uint8_t cp_class(uint32_t cp);

// Canonical combining class (UnicodeData.txt field 3).
uint8_t combining_class(uint32_t cp);

// Canonical decompositions sorted by codepoint, one per entry:
// cp << 43 | first << 22 | second << 1 | primary (second 0 = singleton; primary = NFC recomposes it).
std::span<const uint64_t> decomposition_table();

// Codepoint at s[pos]; *len = bytes consumed (1 for a malformed or truncated lead byte, cp = byte).
inline uint32_t decode_utf8_at(const std::string& s, size_t pos, size_t* len) {
    const auto b = [&](size_t k) { return static_cast<uint32_t>(static_cast<unsigned char>(s[pos + k])); };
    const uint32_t c = b(0);
    size_t n = 1;
    uint32_t cp = c;
    if ((c & 0xE0) == 0xC0) {
        n = 2;
        cp = c & 0x1F;
    } else if ((c & 0xF0) == 0xE0) {
        n = 3;
        cp = c & 0x0F;
    } else if ((c & 0xF8) == 0xF0) {
        n = 4;
        cp = c & 0x07;
    }
    if (n == 1 || pos + n > s.size()) {
        *len = 1;
        return c;
    }
    for (size_t k = 1; k < n; k++)
        cp = (cp << 6) | (b(k) & 0x3F);
    *len = n;
    return cp;
}

}  // namespace imp::unicode
