// GENERATED by tests/refs/gen_chat_goldens.py - do not edit by hand.
//
// Rendered prompts for the chat-template families imp claims to support,
// taken from the upstream templates named above each block and rendered in
// the Jinja configuration transformers uses (#1572). Regenerate with
//   python3 tests/refs/gen_chat_goldens.py --verify
#pragma once

#include <string>
#include <utility>
#include <vector>

namespace chat_goldens {

inline const std::vector<std::pair<std::string, std::string>> k_conv_user_only = {
        {"user", "What is the capital of France?"},
    };
inline const std::vector<std::pair<std::string, std::string>> k_conv_system_user = {
        {"system", "You are a terse assistant."},
        {"user", "Hello there."},
    };
inline const std::vector<std::pair<std::string, std::string>> k_conv_multi_turn = {
        {"user", "Hi"},
        {"assistant", "Hello! How can I help?"},
        {"user", "What is 2+2?"},
    };

// chatml  <-  local:Qwen3-0.6B  (detected family: CHATML)
inline const std::string k_chatml_template =
    "{%- if tools %}\n    {{- '<|im_start|>system\\n' }}\n    {%- if messages[0].role == 'system'"
    " %}\n        {{- messages[0].content + '\\n\\n' }}\n    {%- endif %}\n    {{- \"# Tools\\n\\"
    "nYou may call one or more functions to assist with the user query.\\n\\nYou are provided wit"
    "h function signatures within <tools></tools> XML tags:\\n<tools>\" }}\n    {%- for tool in t"
    "ools %}\n        {{- \"\\n\" }}\n        {{- tool | tojson }}\n    {%- endfor %}\n    {{- \""
    "\\n</tools>\\n\\nFor each function call, return a json object with function name and argumen"
    "ts within <tool_call></tool_call> XML tags:\\n<tool_call>\\n{\\\"name\\\": <function-name>, "
    "\\\"arguments\\\": <args-json-object>}\\n</tool_call><|im_end|>\\n\" }}\n{%- else %}\n    {%"
    "- if messages[0].role == 'system' %}\n        {{- '<|im_start|>system\\n' + messages[0].cont"
    "ent + '<|im_end|>\\n' }}\n    {%- endif %}\n{%- endif %}\n{%- set ns = namespace(multi_step_"
    "tool=true, last_query_index=messages|length - 1) %}\n{%- for message in messages[::-1] %}\n "
    "   {%- set index = (messages|length - 1) - loop.index0 %}\n    {%- if ns.multi_step_tool and"
    " message.role == \"user\" and message.content is string and not(message.content.startswith('"
    "<tool_response>') and message.content.endswith('</tool_response>')) %}\n        {%- set ns.m"
    "ulti_step_tool = false %}\n        {%- set ns.last_query_index = index %}\n    {%- endif %}"
    "\n{%- endfor %}\n{%- for message in messages %}\n    {%- if message.content is string %}\n  "
    "      {%- set content = message.content %}\n    {%- else %}\n        {%- set content = '' %}"
    "\n    {%- endif %}\n    {%- if (message.role == \"user\") or (message.role == \"system\" and"
    " not loop.first) %}\n        {{- '<|im_start|>' + message.role + '\\n' + content + '<|im_end"
    "|>' + '\\n' }}\n    {%- elif message.role == \"assistant\" %}\n        {%- set reasoning_con"
    "tent = '' %}\n        {%- if message.reasoning_content is string %}\n            {%- set rea"
    "soning_content = message.reasoning_content %}\n        {%- else %}\n            {%- if '</th"
    "ink>' in content %}\n                {%- set reasoning_content = content.split('</think>')[0"
    "].rstrip('\\n').split('<think>')[-1].lstrip('\\n') %}\n                {%- set content = con"
    "tent.split('</think>')[-1].lstrip('\\n') %}\n            {%- endif %}\n        {%- endif %}"
    "\n        {%- if loop.index0 > ns.last_query_index %}\n            {%- if loop.last or (not "
    "loop.last and reasoning_content) %}\n                {{- '<|im_start|>' + message.role + '\\"
    "n<think>\\n' + reasoning_content.strip('\\n') + '\\n</think>\\n\\n' + content.lstrip('\\n') "
    "}}\n            {%- else %}\n                {{- '<|im_start|>' + message.role + '\\n' + con"
    "tent }}\n            {%- endif %}\n        {%- else %}\n            {{- '<|im_start|>' + mes"
    "sage.role + '\\n' + content }}\n        {%- endif %}\n        {%- if message.tool_calls %}\n"
    "            {%- for tool_call in message.tool_calls %}\n                {%- if (loop.first a"
    "nd content) or (not loop.first) %}\n                    {{- '\\n' }}\n                {%- en"
    "dif %}\n                {%- if tool_call.function %}\n                    {%- set tool_call "
    "= tool_call.function %}\n                {%- endif %}\n                {{- '<tool_call>\\n{"
    "\"name\": \"' }}\n                {{- tool_call.name }}\n                {{- '\", \"argument"
    "s\": ' }}\n                {%- if tool_call.arguments is string %}\n                    {{- "
    "tool_call.arguments }}\n                {%- else %}\n                    {{- tool_call.argum"
    "ents | tojson }}\n                {%- endif %}\n                {{- '}\\n</tool_call>' }}\n "
    "           {%- endfor %}\n        {%- endif %}\n        {{- '<|im_end|>\\n' }}\n    {%- elif"
    " message.role == \"tool\" %}\n        {%- if loop.first or (messages[loop.index0 - 1].role !"
    "= \"tool\") %}\n            {{- '<|im_start|>user' }}\n        {%- endif %}\n        {{- '\\"
    "n<tool_response>\\n' }}\n        {{- content }}\n        {{- '\\n</tool_response>' }}\n     "
    "   {%- if loop.last or (messages[loop.index0 + 1].role != \"tool\") %}\n            {{- '<|i"
    "m_end|>\\n' }}\n        {%- endif %}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation"
    "_prompt %}\n    {{- '<|im_start|>assistant\\n' }}\n    {%- if enable_thinking is defined and"
    " enable_thinking is false %}\n        {{- '<think>\\n\\n</think>\\n\\n' }}\n    {%- endif %}"
    "\n{%- endif %}"
    ;
inline const std::string k_chatml_bos =
    ""
    ;
inline const std::string k_chatml_eos =
    "<|im_end|>"
    ;
inline const std::string k_chatml_user_only =
    "<|im_start|>user\nWhat is the capital of France?<|im_end|>\n<|im_start|>assistant\n"
    ;
inline const std::string k_chatml_system_user =
    "<|im_start|>system\nYou are a terse assistant.<|im_end|>\n<|im_start|>user\nHello there.<|im"
    "_end|>\n<|im_start|>assistant\n"
    ;
inline const std::string k_chatml_multi_turn =
    "<|im_start|>user\nHi<|im_end|>\n<|im_start|>assistant\nHello! How can I help?<|im_end|>\n<|i"
    "m_start|>user\nWhat is 2+2?<|im_end|>\n<|im_start|>assistant\n"
    ;

// chatml_nemotron_nano  <-  local:Nemotron-3-Nano-30B-A3B-NVFP4  (detected family: CHATML)
inline const std::string k_chatml_nemotron_nano_template =
    "{% macro render_extra_keys(json_dict, handled_keys) %}\n    {%- if json_dict is mapping %}\n"
    "        {%- for json_key in json_dict if json_key not in handled_keys %}\n            {%- if"
    " json_dict[json_key] is mapping or (json_dict[json_key] is sequence and json_dict[json_key] "
    "is not string) %}\n                {{- '\\n<' ~ json_key ~ '>' ~ (json_dict[json_key] | tojs"
    "on | safe) ~ '</' ~ json_key ~ '>' }}\n            {%- else %}\n                {{-'\\n<' ~ "
    "json_key ~ '>' ~ (json_dict[json_key] | string) ~ '</' ~ json_key ~ '>' }}\n            {%- "
    "endif %}\n        {%- endfor %}\n    {%- endif %}\n{% endmacro %}\n{%- set enable_thinking ="
    " enable_thinking if enable_thinking is defined else True %}\n{%- set truncate_history_thinki"
    "ng = truncate_history_thinking if truncate_history_thinking is defined else True %}\n\n{%- s"
    "et ns = namespace(last_user_idx = -1) %}\n{%- set loop_messages = messages %}\n{%- for m in "
    "loop_messages %}\n  {%- if m[\"role\"] == \"user\" %}\n    {%- set ns.last_user_idx = loop.i"
    "ndex0 %}\n  {%- endif %}\n{%- endfor %}\n\n{%- if messages[0][\"role\"] == \"system\" %}\n  "
    "  {%- set system_message = messages[0][\"content\"] %}\n    {%- set loop_messages = messages"
    "[1:] %}\n{%- else %}\n    {%- set system_message = \"\" %}\n    {%- set loop_messages = mess"
    "ages %}\n{%- endif %}\n{%- if not tools is defined %}\n    {%- set tools = [] %}\n{%- endif "
    "%}\n{# Recompute last_user_idx relative to loop_messages after handling system #}\n{%- set n"
    "s = namespace(last_user_idx = -1) %}\n{%- for m in loop_messages %}\n  {%- if m[\"role\"] =="
    " \"user\" %}\n    {%- set ns.last_user_idx = loop.index0 %}\n  {%- endif %}\n{%- endfor %}\n"
    "{%- if system_message is defined %}\n    {{- \"<|im_start|>system\\n\" + system_message }}\n"
    "{%- else %}\n    {%- if tools is iterable and tools | length > 0 %}\n        {{- \"<|im_star"
    "t|>system\\n\" }}\n    {%- endif %}\n{%- endif %}\n{%- if tools is iterable and tools | leng"
    "th > 0 %}\n    {%- if system_message is defined and system_message | length > 0 %}\n        "
    "{{- \"\\n\\n\" }}\n    {%- endif %}\n    {{- \"# Tools\\n\\nYou have access to the following"
    " functions:\\n\\n\" }}\n    {{- \"<tools>\" }}\n    {%- for tool in tools %}\n        {%- if"
    " tool.function is defined %}\n            {%- set tool = tool.function %}\n        {%- endif"
    " %}\n        {{- \"\\n<function>\\n<name>\" ~ tool.name ~ \"</name>\" }}\n        {%- if too"
    "l.description is defined %}\n            {{- '\\n<description>' ~ (tool.description | trim) "
    "~ '</description>' }}\n        {%- endif %}\n        {{- '\\n<parameters>' }}\n        {%- i"
    "f tool.parameters is defined and tool.parameters is mapping and tool.parameters.properties i"
    "s defined and tool.parameters.properties is mapping %}\n            {%- for param_name, para"
    "m_fields in tool.parameters.properties|items %}\n                {{- '\\n<parameter>' }}\n  "
    "              {{- '\\n<name>' ~ param_name ~ '</name>' }}\n                {%- if param_fiel"
    "ds.type is defined %}\n                    {{- '\\n<type>' ~ (param_fields.type | string) ~ "
    "'</type>' }}\n                {%- endif %}\n                {%- if param_fields.description "
    "is defined %}\n                    {{- '\\n<description>' ~ (param_fields.description | trim"
    ") ~ '</description>' }}\n                {%- endif %}\n                {%- if param_fields.e"
    "num is defined %}\n                    {{- '\\n<enum>' ~ (param_fields.enum | tojson | safe)"
    " ~ '</enum>' }}\n                {%- endif %}\n                {%- set handled_keys = ['name"
    "', 'type', 'description', 'enum'] %}\n                {{- render_extra_keys(param_fields, ha"
    "ndled_keys) }}\n                {{- '\\n</parameter>' }}\n            {%- endfor %}\n       "
    " {%- endif %}\n        {% set handled_keys = ['type', 'properties', 'required'] %}\n        "
    "{{- render_extra_keys(tool.parameters, handled_keys) }}\n        {%- if tool.parameters is d"
    "efined and tool.parameters.required is defined %}\n            {{- '\\n<required>' ~ (tool.p"
    "arameters.required | tojson | safe) ~ '</required>' }}\n        {%- endif %}\n        {{- '"
    "\\n</parameters>' }}\n        {%- set handled_keys = ['type', 'name', 'description', 'parame"
    "ters'] %}\n        {{- render_extra_keys(tool, handled_keys) }}\n        {{- '\\n</function>"
    "' }}\n    {%- endfor %}\n    {{- \"\\n</tools>\" }}\n\n    {{- '\\n\\nIf you choose to call "
    "a function ONLY reply in the following format with NO suffix:\\n\\n<tool_call>\\n<function=e"
    "xample_function_name>\\n<parameter=example_parameter_1>\\nvalue_1\\n</parameter>\\n<paramete"
    "r=example_parameter_2>\\nThis is the value for the second parameter\\nthat can span\\nmultip"
    "le lines\\n</parameter>\\n</function>\\n</tool_call>\\n\\n<IMPORTANT>\\nReminder:\\n- Functi"
    "on calls MUST follow the specified format: an inner <function=...></function> block must be "
    "nested within <tool_call></tool_call> XML tags\\n- Required parameters MUST be specified\\n-"
    " You may provide optional reasoning for your function call in natural language BEFORE the fu"
    "nction call, but NOT after\\n- If there is no function call available, answer the question l"
    "ike normal with your current knowledge and do not tell the user about function calls\\n</IMP"
    "ORTANT>' }}\n{%- endif %}\n\n\n{%- if system_message is defined %}\n    {{- '<|im_end|>\\n' "
    "}}\n{%- else %}\n    {%- if tools is iterable and tools | length > 0 %}\n        {{- '<|im_e"
    "nd|>\\n' }}\n    {%- endif %}\n{%- endif %}\n\n{%- for message in loop_messages %}\n    {%- "
    "if message.role == \"assistant\" %}\n        {# Add reasoning content in to content field fo"
    "r unified processing below. #}\n        {%- if message.reasoning_content is defined and mess"
    "age.reasoning_content is string and message.reasoning_content | trim | length > 0 %}\n      "
    "      {%- set content = \"<think>\\n\" ~ message.reasoning_content ~ \"\\n</think>\\n\" ~ (m"
    "essage.content | default('', true)) %}\n        {%- else %}\n            {%- set content = m"
    "essage.content | default('', true) %}\n            {%- if content is string -%}\n           "
    "     {# Allow downstream logic to to take care of broken thought, only handle coherent reaso"
    "ning here. #}\n                {%- if '<think>' not in content and '</think>' not in content"
    " -%}\n                    {%- set content = \"<think></think>\" ~ content -%}\n             "
    "   {%- endif -%}\n            {%- else -%}\n                {%- set content = content -%}\n "
    "           {%- endif -%}\n        {%- endif %}\n        {%- if message.tool_calls is defined"
    " and message.tool_calls is iterable and message.tool_calls | length > 0 %}\n            {# A"
    "ssistant message has tool calls. #}\n            {{- '<|im_start|>assistant\\n' }}\n        "
    "        {%- set include_content = not (truncate_history_thinking and loop.index0 < ns.last_u"
    "ser_idx) %}\n                {%- if content is string and content | trim | length > 0 %}\n  "
    "                  {%- if include_content %}\n                        {{- (content | trim) ~ "
    "'\\n' -}}\n                    {%- else %}\n                        {%- set c = (content | s"
    "tring) %}\n                        {%- if '</think>' in c %}\n                            {#"
    " Keep only content after the last closing think. Also generation prompt causes this. #}\n   "
    "                         {%- set c = c.split('</think>')[-1] %}\n                        {%-"
    " elif '<think>' in c %}\n                            {# If <think> was opened but never clos"
    "ed, drop the trailing think segment #}\n                            {%- set c = c.split('<th"
    "ink>')[0] %}\n                        {%- endif %}\n                        {%- set c = \"<t"
    "hink></think>\" ~ c | trim %}\n                        {%- if c | length > 0 %}\n           "
    "                 {{- c ~ '\\n' -}}\n                        {%- endif %}\n                  "
    "  {%- endif %}\n                {%- else %}\n                    {{- \"<think></think>\" -}}"
    "\n                {%- endif %}\n                {%- for tool_call in message.tool_calls %}\n"
    "                    {%- if tool_call.function is defined %}\n                        {%- set"
    " tool_call = tool_call.function %}\n                    {%- endif %}\n                    {{"
    "- '<tool_call>\\n<function=' ~ tool_call.name ~ '>\\n' -}}\n                        {%- if t"
    "ool_call.arguments is defined %}\n                            {%- for args_name, args_value "
    "in tool_call.arguments|items %}\n                                {{- '<parameter=' ~ args_na"
    "me ~ '>\\n' -}}\n                                    {%- set args_value = args_value | tojso"
    "n | safe if args_value is mapping or (args_value is sequence and args_value is not string) e"
    "lse args_value | string %}\n                                {{- args_value ~ '\\n</parameter"
    ">\\n' -}}\n                            {%- endfor %}\n                        {%- endif %}\n"
    "                    {{- '</function>\\n</tool_call>\\n' -}}\n                {%- endfor %}\n"
    "                {{- '<|im_end|>\\n' }}\n        {%- else %}\n            {# Assistant messag"
    "e doesn't have tool calls. #}\n            {%- if not (truncate_history_thinking and loop.in"
    "dex0 < ns.last_user_idx) %}\n                {{- '<|im_start|>assistant\\n' ~ (content | def"
    "ault('', true) | string | trim) ~ '<|im_end|>\\n' }}\n            {%- else %}\n             "
    "   {%- set c = (content | default('', true) | string) %}\n                {%- if '<think>' i"
    "n c and '</think>' in c %}\n                    {%- set c = \"<think></think>\" ~ c.split('<"
    "/think>')[-1] %}\n                {%- endif %}\n                {%- set c = c | trim %}\n   "
    "             {%- if c | length > 0 %}\n                    {{- '<|im_start|>assistant\\n' ~ "
    "c ~ '<|im_end|>\\n' }}\n                {%- else %}\n                    {{- '<|im_start|>as"
    "sistant\\n<|im_end|>\\n' }}\n                {%- endif %}\n            {%- endif %}\n       "
    " {%- endif %}\n    {%- elif message.role == \"user\" or message.role == \"system\" %}\n     "
    "   {{- '<|im_start|>' + message.role + '\\n' }}\n        {%- set content = message.content |"
    " string %}\n        {{- content }}\n        {{- '<|im_end|>\\n' }}\n    {%- elif message.rol"
    "e == \"tool\" %}\n        {%- if loop.previtem and loop.previtem.role != \"tool\" %}\n      "
    "      {{- '<|im_start|>user\\n' }}\n        {%- endif %}\n        {{- '<tool_response>\\n' }"
    "}\n        {{- message.content }}\n        {{- '\\n</tool_response>\\n' }}\n        {%- if n"
    "ot loop.last and loop.nextitem.role != \"tool\" %}\n            {{- '<|im_end|>\\n' }}\n    "
    "    {%- elif loop.last %}\n            {{- '<|im_end|>\\n' }}\n        {%- endif %}\n    {%-"
    " else %}\n        {{- '<|im_start|>' + message.role + '\\n' + message.content + '<|im_end|>"
    "\\n' }}\n    {%- endif %}\n{%- endfor %}\n\n{%- if add_generation_prompt %}\n    {%- if enab"
    "le_thinking %}\n        {{- '<|im_start|>assistant\\n<think>\\n' }}\n    {%- else %}\n      "
    "  {{- '<|im_start|>assistant\\n<think></think>' }}\n    {%- endif %}\n{%- endif %}\n"
    ;
inline const std::string k_chatml_nemotron_nano_bos =
    "<s>"
    ;
inline const std::string k_chatml_nemotron_nano_eos =
    "<|im_end|>"
    ;
inline const std::string k_chatml_nemotron_nano_user_only =
    "<|im_start|>system\n<|im_end|>\n<|im_start|>user\nWhat is the capital of France?<|im_end|>\n"
    "<|im_start|>assistant\n<think>\n"
    ;
inline const std::string k_chatml_nemotron_nano_system_user =
    "<|im_start|>system\nYou are a terse assistant.<|im_end|>\n<|im_start|>user\nHello there.<|im"
    "_end|>\n<|im_start|>assistant\n<think>\n"
    ;
inline const std::string k_chatml_nemotron_nano_multi_turn =
    "<|im_start|>system\n<|im_end|>\n<|im_start|>user\nHi<|im_end|>\n<|im_start|>assistant\n<thin"
    "k></think>Hello! How can I help?<|im_end|>\n<|im_start|>user\nWhat is 2+2?<|im_end|>\n<|im_s"
    "tart|>assistant\n<think>\n"
    ;

// gemma  <-  local:Gemma-4-12B-NVFP4  (detected family: GEMMA)
inline const std::string k_gemma_template =
    "{#\n  Template: Google Gemma 4 Canonical Chat Template\n  Author: Google Gemma Engineering T"
    "eam\n  Published: 2026-07-09\n  Context: Fixed tool-calling loops, turn closures, and thinki"
    "ng content-ordering.\n#}\n{%- macro format_parameters(properties, required, filter_keys=fals"
    "e) -%}\n    {%- set standard_keys = ['description', 'type', 'properties', 'required', 'nulla"
    "ble'] -%}\n    {%- set ns = namespace(found_first=false) -%}\n    {%- for key, value in prop"
    "erties | dictsort -%}\n        {%- set add_comma = false -%}\n        {%- if not filter_keys"
    " or key not in standard_keys -%}\n            {%- if ns.found_first %},{% endif -%}\n       "
    "     {%- set ns.found_first = true -%}\n            {{ key }}:{\n            {%- if value['d"
    "escription'] -%}\n                description:<|\"|>{{ value['description'] }}<|\"|>\n      "
    "          {%- set add_comma = true -%}\n            {%- endif -%}\n            {%- if value["
    "'type'] | upper == 'STRING' -%}\n                {%- if value['enum'] -%}\n                 "
    "   {%- if add_comma %},{%- else -%} {%- set add_comma = true -%} {% endif -%}\n             "
    "       enum:{{ format_argument(value['enum']) }}\n                {%- endif -%}\n           "
    " {%- elif value['type'] | upper == 'ARRAY' -%}\n                {%- if value['items'] is map"
    "ping and value['items'] -%}\n                    {%- if add_comma %},{%- else -%} {%- set ad"
    "d_comma = true -%} {% endif -%}\n                    items:{\n                    {%- set ns"
    "_items = namespace(found_first=false) -%}\n                    {%- for item_key, item_value "
    "in value['items'] | dictsort -%}\n                        {%- if item_value is not none -%}"
    "\n                            {%- if ns_items.found_first %},{% endif -%}\n                 "
    "           {%- set ns_items.found_first = true -%}\n                            {%- if item_"
    "key == 'properties' -%}\n                                properties:{\n                     "
    "           {%- if item_value is mapping -%}\n                                    {{- format_"
    "parameters(item_value, value['items']['required'] | default([])) -}}\n                      "
    "          {%- endif -%}\n                                }\n                            {%- "
    "elif item_key == 'required' -%}\n                                required:[\n               "
    "                 {%- for req_item in item_value -%}\n                                    <|"
    "\"|>{{- req_item -}}<|\"|>\n                                    {%- if not loop.last %},{% e"
    "ndif -%}\n                                {%- endfor -%}\n                                ]"
    "\n                            {%- elif item_key == 'type' -%}\n                             "
    "   {%- if item_value is string -%}\n                                    type:{{ format_argum"
    "ent(item_value | upper) }}\n                                {%- else -%}\n                  "
    "                  type:{{ format_argument(item_value | map('upper') | list) }}\n            "
    "                    {%- endif -%}\n                            {%- else -%}\n               "
    "                 {{ item_key }}:{{ format_argument(item_value) }}\n                         "
    "   {%- endif -%}\n                        {%- endif -%}\n                    {%- endfor -%}"
    "\n                    }\n                {%- endif -%}\n            {%- endif -%}\n         "
    "   {%- if value['nullable'] %}\n                {%- if add_comma %},{%- else -%} {%- set add"
    "_comma = true -%} {% endif -%}\n                nullable:true\n            {%- endif -%}\n  "
    "          {%- if value['type'] | upper == 'OBJECT' -%}\n                {%- if value['proper"
    "ties'] is defined and value['properties'] is mapping -%}\n                    {%- if add_com"
    "ma %},{%- else -%} {%- set add_comma = true -%} {% endif -%}\n                    properties"
    ":{\n                    {{- format_parameters(value['properties'], value['required'] | defau"
    "lt([])) -}}\n                    }\n                {%- elif value is mapping -%}\n         "
    "           {%- if add_comma %},{%- else -%} {%- set add_comma = true -%} {% endif -%}\n     "
    "               properties:{\n                    {{- format_parameters(value, value['require"
    "d'] | default([]), filter_keys=true) -}}\n                    }\n                {%- endif -"
    "%}\n                {%- if value['required'] -%}\n                    {%- if add_comma %},{%"
    "- else -%} {%- set add_comma = true -%} {% endif -%}\n                    required:[\n      "
    "              {%- for item in value['required'] | default([]) -%}\n                        <"
    "|\"|>{{- item -}}<|\"|>\n                        {%- if not loop.last %},{% endif -%}\n     "
    "               {%- endfor -%}\n                    ]\n                {%- endif -%}\n       "
    "     {%- endif -%}\n            {%- if add_comma %},{%- else -%} {%- set add_comma = true -%"
    "} {% endif -%}\n            type:<|\"|>{{ value['type'] | upper }}<|\"|>}\n        {%- endif"
    " -%}\n    {%- endfor -%}\n{%- endmacro -%}\n{%- macro format_function_declaration(tool_data)"
    " -%}\n    declaration:{{- tool_data['function']['name'] -}}{description:<|\"|>{{- tool_data["
    "'function']['description'] -}}<|\"|>\n    {%- set params = tool_data['function']['parameters"
    "'] -%}\n    {%- if params -%}\n        ,parameters:{\n        {%- if params['properties'] -%"
    "}\n            properties:{ {{- format_parameters(params['properties'], params['required']) "
    "-}} },\n        {%- endif -%}\n        {%- if params['required'] -%}\n            required:["
    "\n            {%- for item in params['required'] -%}\n                <|\"|>{{- item -}}<|\""
    "|>\n                {{- ',' if not loop.last -}}\n            {%- endfor -%}\n            ],"
    "\n        {%- endif -%}\n        {%- if params['type'] -%}\n            type:<|\"|>{{- param"
    "s['type'] | upper -}}<|\"|>}\n        {%- endif -%}\n    {%- endif -%}\n    {%- if 'response"
    "' in tool_data['function'] -%}\n        {%- set response_declaration = tool_data['function']"
    "['response'] -%}\n        ,response:{\n        {%- if response_declaration['description'] -%"
    "}\n            description:<|\"|>{{- response_declaration['description'] -}}<|\"|>,\n       "
    " {%- endif -%}\n        {%- if response_declaration['type'] | upper == 'OBJECT' -%}\n       "
    "     type:<|\"|>{{- response_declaration['type'] | upper -}}<|\"|>}\n        {%- endif -%}\n"
    "    {%- endif -%}\n    }\n{%- endmacro -%}\n{%- macro format_argument(argument, escape_keys="
    "True) -%}\n    {%- if argument is none -%}\n        {{- 'null' -}}\n    {%- elif argument is"
    " string -%}\n        {{- '<|\"|>' + argument + '<|\"|>' -}}\n    {%- elif argument is boolea"
    "n -%}\n        {{- 'true' if argument else 'false' -}}\n    {%- elif argument is mapping -%}"
    "\n        {{- '{' -}}\n        {%- set ns = namespace(found_first=false) -%}\n        {%- fo"
    "r key, value in argument | dictsort -%}\n            {%- if ns.found_first %},{% endif -%}\n"
    "            {%- set ns.found_first = true -%}\n            {%- if escape_keys -%}\n         "
    "       {{- '<|\"|>' + key + '<|\"|>' -}}\n            {%- else -%}\n                {{- key "
    "-}}\n            {%- endif -%}\n            :{{- format_argument(value, escape_keys=escape_k"
    "eys) -}}\n        {%- endfor -%}\n        {{- '}' -}}\n    {%- elif argument is sequence -%}"
    "\n        {{- '[' -}}\n        {%- for item in argument -%}\n            {{- format_argument"
    "(item, escape_keys=escape_keys) -}}\n            {%- if not loop.last %},{% endif -%}\n     "
    "   {%- endfor -%}\n        {{- ']' -}}\n    {%- else -%}\n        {{- argument -}}\n    {%- "
    "endif -%}\n{%- endmacro -%}\n{%- macro strip_thinking(text) -%}\n    {%- set ns = namespace("
    "result='') -%}\n    {%- for part in text.split('<channel|>') -%}\n        {%- if '<|channel>"
    "' in part -%}\n            {%- set ns.result = ns.result + part.split('<|channel>')[0] -%}\n"
    "        {%- else -%}\n            {%- set ns.result = ns.result + part -%}\n        {%- endi"
    "f -%}\n    {%- endfor -%}\n    {{- ns.result | trim -}}\n{%- endmacro -%}\n\n{%- macro forma"
    "t_tool_response_block(tool_name, response) -%}\n    {{- '<|tool_response>' -}}\n    {%- if r"
    "esponse is mapping -%}\n        {{- 'response:' + tool_name + '{' -}}\n        {%- for key, "
    "value in response | dictsort -%}\n            {{- key -}}:{{- format_argument(value, escape_"
    "keys=False) -}}\n            {%- if not loop.last %},{% endif -%}\n        {%- endfor -%}\n "
    "       {{- '}' -}}\n    {%- else -%}\n        {{- 'response:' + tool_name + '{value:' + form"
    "at_argument(response, escape_keys=False) + '}' -}}\n    {%- endif -%}\n    {{- '<tool_respon"
    "se|>' -}}\n{%- endmacro -%}\n\n{#- ===== SETUP ===== -#}\n{%- set ns = namespace(prev_messag"
    "e_type=None, prev_non_tool_role=None) -%}\n{%- set loop_messages = messages -%}\n{%- set ena"
    "ble_thinking = enable_thinking | default(false) -%}\n{%- set preserve_thinking = preserve_th"
    "inking | default(false) -%}\n{{- bos_token -}}\n{#- Handle System/Tool Definitions Block -#}"
    "\n{%- if enable_thinking or tools or (messages and messages[0]['role'] in ['system', 'develo"
    "per']) -%}\n    {{- '<|turn>system\\n' -}}\n    {#- Inject Thinking token at the very top of"
    " the FIRST system turn -#}\n    {%- if enable_thinking -%}\n        {{- '<|think|>\\n' -}}\n"
    "        {%- set ns.prev_message_type = 'think' -%}\n    {%- endif -%}\n    {%- if messages a"
    "nd messages[0]['role'] in ['system', 'developer'] -%}\n        {%- if messages[0]['content']"
    " is string -%}\n            {{- messages[0]['content'] | trim -}}\n        {%- elif messages"
    "[0]['content'] is sequence -%}\n            {%- for item in messages[0]['content'] -%}\n    "
    "            {{- item['text'] | trim + ' '-}}\n            {%- endfor -%}\n        {%- endif "
    "-%}\n        {%- set loop_messages = messages[1:] -%}\n    {%- endif -%}\n    {%- if tools -"
    "%}\n        {%- for tool in tools %}\n            {{- '<|tool>' -}}\n            {{- format_"
    "function_declaration(tool) | trim -}}\n            {{- '<tool|>' -}}\n        {%- endfor %}"
    "\n        {%- set ns.prev_message_type = 'tool' -%}\n    {%- endif -%}\n    {{- '<turn|>\\n'"
    " -}}\n{%- endif %}\n\n{#- Pre-scan: find last user message index for reasoning guard -#}\n{%"
    "- set ns_turn = namespace(last_user_idx=-1) -%}\n{%- for i in range(loop_messages | length) "
    "-%}\n    {%- if loop_messages[i]['role'] == 'user' -%}\n        {%- set ns_turn.last_user_id"
    "x = i -%}\n    {%- endif -%}\n{%- endfor -%}\n\n{#- Loop through messages -#}\n{%- for messa"
    "ge in loop_messages -%}\n    {%- if message['role'] != 'tool' -%}\n    {%- set ns.prev_messa"
    "ge_type = None -%}\n    {%- set role = 'model' if message['role'] == 'assistant' else messag"
    "e['role'] -%}\n    {#- Detect continuation using tracked state — O(1) instead of O(n) backwa"
    "rd scan -#}\n    {%- set continue_same_model_turn = (role == 'model' and ns.prev_non_tool_ro"
    "le == 'assistant') -%}\n    {%- if not continue_same_model_turn -%}\n        {{- '<|turn>' +"
    " role + '\\n' }}\n\n    {%- endif -%}\n\n    {#- Render reasoning/reasoning_content as think"
    "ing channel -#}\n    {%- set thinking_text = message.get('reasoning') or message.get('reason"
    "ing_content') -%}\n    {%- set thinking_gate = (loop.index0 > ns_turn.last_user_idx) or (pre"
    "serve_thinking and message.get('tool_calls')) -%}\n    {%- if thinking_text and thinking_gat"
    "e -%}\n        {{- '<|channel>thought\\n' + thinking_text + '\\n<channel|>' -}}\n    {%- end"
    "if -%}\n\n            {%- if message.get('tool_calls') -%}\n                {%- for tool_cal"
    "l in message.get('tool_calls') -%}\n                    {%- set function = tool_call['functi"
    "on'] -%}\n                    {{- '<|tool_call>call:' + function['name'] + '{' -}}\n        "
    "            {%- if function['arguments'] is mapping -%}\n                        {%- set ns_"
    "args = namespace(found_first=false) -%}\n                        {%- for key, value in funct"
    "ion['arguments'] | dictsort -%}\n                            {%- if ns_args.found_first %},{"
    "% endif -%}\n                            {%- set ns_args.found_first = true -%}\n           "
    "                 {{- key -}}:{{- format_argument(value, escape_keys=False) -}}\n            "
    "            {%- endfor -%}\n                    {%- elif function['arguments'] is none -%}\n"
    "                    {%- else -%}\n                        {{- raise_exception(\n            "
    "                \"chat_template: tool_calls[].function.arguments must be a \"\n             "
    "               \"JSON object (mapping), not a string. Deserialize arguments \"\n            "
    "                \"before passing to the template.\"\n                        ) -}}\n        "
    "            {%- endif -%}\n                    {{- '}<tool_call|>' -}}\n                {%- "
    "endfor -%}\n                {%- set ns.prev_message_type = 'tool_call' -%}\n            {%- "
    "endif -%}\n\n            {%- set ns_tr_out = namespace(flag=false) -%}\n            {%- if m"
    "essage.get('tool_responses') -%}\n                {#- Legacy: tool_responses embedded on the"
    " assistant message (Google/Gemma native) -#}\n                {%- for tool_response in messa"
    "ge.get('tool_responses') -%}\n                    {{- format_tool_response_block(tool_respon"
    "se['name'] | default('unknown', true), tool_response['response']) -}}\n                    {"
    "%- set ns_tr_out.flag = true -%}\n                    {%- set ns.prev_message_type = 'tool_r"
    "esponse' -%}\n                {%- endfor -%}\n            {%- elif message.get('tool_calls')"
    " -%}\n                {#- OpenAI Chat Completions: forward-scan consecutive role:tool messag"
    "es -#}\n                {%- set ns_tool_scan = namespace(stopped=false) -%}\n               "
    " {%- for k in range(loop.index0 + 1, loop_messages | length) -%}\n                    {%- if"
    " ns_tool_scan.stopped -%}\n                    {%- elif loop_messages[k]['role'] != 'tool' -"
    "%}\n                        {%- set ns_tool_scan.stopped = true -%}\n                    {%-"
    " else -%}\n                        {%- set follow = loop_messages[k] -%}\n                  "
    "      {#- Resolve tool_call_id to function name -#}\n                        {%- set ns_tnam"
    "e = namespace(name=follow.get('name') or 'unknown') -%}\n                        {%- for tc "
    "in message.get('tool_calls') -%}\n                            {%- if tc.get('id') == follow."
    "get('tool_call_id') -%}\n                                {%- set ns_tname.name = tc['functio"
    "n']['name'] -%}\n                            {%- endif -%}\n                        {%- endf"
    "or -%}\n                        {#- Handle content as string or content-parts array -#}\n   "
    "                     {%- set tool_body = follow.get('content') -%}\n                        "
    "{%- if tool_body is string -%}\n                            {{- format_tool_response_block(n"
    "s_tname.name, tool_body) -}}\n                        {%- elif tool_body is sequence and too"
    "l_body is not string -%}\n                            {%- set ns_txt = namespace(s='') -%}\n"
    "                            {%- for part in tool_body -%}\n                                {"
    "%- if part.get('type') == 'text' -%}\n                                    {%- set ns_txt.s ="
    " ns_txt.s + (part.get('text') | default('')) -%}\n                                {%- endif "
    "-%}\n                            {%- endfor -%}\n                            {{- format_tool"
    "_response_block(ns_tname.name, ns_txt.s) -}}\n                            {%- for part in to"
    "ol_body -%}\n                                {%- if part.get('type') in ['image', 'image_url"
    "'] -%}\n                                    {{- '<|image|>' -}}\n                           "
    "     {%- elif part.get('type') in ['audio', 'input_audio'] -%}\n                            "
    "        {{- '<|audio|>' -}}\n                                {%- elif part.get('type') == 'v"
    "ideo' -%}\n                                    {{- '<|video|>' -}}\n                        "
    "        {%- endif -%}\n                            {%- endfor -%}\n                        {"
    "%- else -%}\n                            {{- format_tool_response_block(ns_tname.name, tool_"
    "body) -}}\n                        {%- endif -%}\n                        {%- set ns_tr_out."
    "flag = true -%}\n                        {%- set ns.prev_message_type = 'tool_response' -%}"
    "\n                    {%- endif -%}\n                {%- endfor -%}\n            {%- endif -"
    "%}\n\n            {%- set captured_content -%}\n            {%- if message.get('content') is"
    " string -%}\n                {%- if role == 'model' -%}\n                    {{- strip_think"
    "ing(message['content']) -}}\n                {%- else -%}\n                    {{- message['"
    "content'] | trim -}}\n                {%- endif -%}\n            {%- elif message.get('conte"
    "nt') is sequence -%}\n                {%- for item in message['content'] -%}\n              "
    "      {%- if item.get('type') == 'text' -%}\n                        {%- if role == 'model' "
    "-%}\n                            {{- strip_thinking(item['text']) -}}\n                     "
    "   {%- else -%}\n                            {{- item['text'] | trim -}}\n                  "
    "      {%- endif -%}\n                    {%- elif item.get('type') in ['image', 'image_url']"
    " -%}\n                        {{- '<|image|>' -}}\n                    {%- elif item.get('ty"
    "pe') in ['audio', 'input_audio'] -%}\n                        {{- '<|audio|>' -}}\n         "
    "           {%- elif item.get('type') == 'video' -%}\n                        {{- '<|video|>'"
    " -}}\n                    {%- endif -%}\n                {%- endfor -%}\n            {%- end"
    "if -%}\n            {%- endset -%}\n\n            {{- captured_content -}}\n            {%- "
    "set has_content = captured_content | trim | length > 0 -%}\n\n        {#- Forward-scan: find"
    " next non-tool message role for continuation detection -#}\n        {%- set next_nt = namesp"
    "ace(role=None, found=false) -%}\n        {%- for j in range(loop.index0 + 1, loop_messages |"
    " length) -%}\n            {%- if not next_nt.found -%}\n                {%- if loop_messages"
    "[j]['role'] != 'tool' -%}\n                    {%- set next_nt.role = loop_messages[j]['role"
    "'] -%}\n                    {%- set next_nt.found = true -%}\n                {%- endif -%}"
    "\n            {%- endif -%}\n        {%- endfor -%}\n\n        {%- set continues_into_next ="
    " (\n            role == 'model'\n            and next_nt.role == 'assistant'\n            an"
    "d (not message.get('tool_calls') or ns_tr_out.flag)\n        ) -%}\n\n        {%- if ns.prev"
    "_message_type == 'tool_call' and not ns_tr_out.flag -%}\n            {{- '<|tool_response>' "
    "-}}\n        {%- elif continues_into_next -%}\n        {%- elif not (ns_tr_out.flag and not "
    "has_content and not next_nt.found) -%}\n            {{- '<turn|>\\n' -}}\n        {%- endif "
    "-%}\n\n    {#- Track previous non-tool role for next iteration (avoids O(n) backward scan) -"
    "#}\n    {%- set ns.prev_non_tool_role = message['role'] -%}\n    {%- endif -%}\n{%- endfor -"
    "%}\n\n{%- if add_generation_prompt -%}\n    {%- if ns.prev_message_type != 'tool_response' a"
    "nd ns.prev_message_type != 'tool_call' -%}\n        {{- '<|turn>model\\n' -}}\n        {%- i"
    "f not enable_thinking -%}\n            {{- '<|channel>thought\\n<channel|>' -}}\n        {%-"
    " endif -%}\n    {%- elif ns.prev_message_type == 'tool_response' and enable_thinking -%}\n  "
    "      {{- '<|channel>thought\\n' -}}\n    {%- endif -%}\n{%- endif -%}\n"
    ;
inline const std::string k_gemma_bos =
    "<bos>"
    ;
inline const std::string k_gemma_eos =
    "<eos>"
    ;
inline const std::string k_gemma_user_only =
    "<bos><|turn>user\nWhat is the capital of France?<turn|>\n<|turn>model\n<|channel>thought\n<c"
    "hannel|>"
    ;
inline const std::string k_gemma_system_user =
    "<bos><|turn>system\nYou are a terse assistant.<turn|>\n<|turn>user\nHello there.<turn|>\n<|t"
    "urn>model\n<|channel>thought\n<channel|>"
    ;
inline const std::string k_gemma_multi_turn =
    "<bos><|turn>user\nHi<turn|>\n<|turn>model\nHello! How can I help?<turn|>\n<|turn>user\nWhat "
    "is 2+2?<turn|>\n<|turn>model\n<|channel>thought\n<channel|>"
    ;

// llama3  <-  NousResearch/Meta-Llama-3-8B-Instruct  (detected family: LLAMA3)
inline const std::string k_llama3_template =
    "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|star"
    "t_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|e"
    "ot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ con"
    "tent }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_heade"
    "r_id|>\n\n' }}{% endif %}"
    ;
inline const std::string k_llama3_bos =
    "<|begin_of_text|>"
    ;
inline const std::string k_llama3_eos =
    "<|eot_id|>"
    ;
inline const std::string k_llama3_user_only =
    "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nWhat is the capital of France?<"
    "|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
    ;
inline const std::string k_llama3_system_user =
    "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are a terse assistant.<|e"
    "ot_id|><|start_header_id|>user<|end_header_id|>\n\nHello there.<|eot_id|><|start_header_id|>"
    "assistant<|end_header_id|>\n\n"
    ;
inline const std::string k_llama3_multi_turn =
    "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nHi<|eot_id|><|start_header_id|>"
    "assistant<|end_header_id|>\n\nHello! How can I help?<|eot_id|><|start_header_id|>user<|end_h"
    "eader_id|>\n\nWhat is 2+2?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
    ;

// llama2  <-  unsloth/mistral-7b-instruct-v0.2  (detected family: LLAMA2)
inline const std::string k_llama2_template =
    "{%- if messages[0]['role'] == 'system' %}\n    {%- set system_message = messages[0]['content"
    "'] %}\n    {%- set loop_messages = messages[1:] %}\n{%- else %}\n    {%- set loop_messages ="
    " messages %}\n{%- endif %}\n\n{{- bos_token }}\n{%- for message in loop_messages %}\n    {%-"
    " if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}\n        {{- raise_exception('A"
    "fter the optional system message, conversation roles must alternate user/assistant/user/assi"
    "stant/...') }}\n    {%- endif %}\n    {%- if message['role'] == 'user' %}\n        {%- if lo"
    "op.first and system_message is defined %}\n            {{- ' [INST] ' + system_message + '\\"
    "n\\n' + message['content'] + ' [/INST]' }}\n        {%- else %}\n            {{- ' [INST] ' "
    "+ message['content'] + ' [/INST]' }}\n        {%- endif %}\n    {%- elif message['role'] == "
    "'assistant' %}\n        {{- ' ' + message['content'] + eos_token}}\n    {%- else %}\n       "
    " {{- raise_exception('Only user and assistant roles are supported, with the exception of an "
    "initial optional system message!') }}\n    {%- endif %}\n{%- endfor %}\n"
    ;
inline const std::string k_llama2_bos =
    "<s>"
    ;
inline const std::string k_llama2_eos =
    "</s>"
    ;
inline const std::string k_llama2_user_only =
    "<s> [INST] What is the capital of France? [/INST]"
    ;
inline const std::string k_llama2_system_user =
    "<s> [INST] You are a terse assistant.\n\nHello there. [/INST]"
    ;
inline const std::string k_llama2_multi_turn =
    "<s> [INST] Hi [/INST] Hello! How can I help?</s> [INST] What is 2+2? [/INST]"
    ;

// mistral_v3  <-  unsloth/mistral-7b-instruct-v0.3  (detected family: MISTRAL_V3)
inline const std::string k_mistral_v3_template =
    "{%- if messages[0][\"role\"] == \"system\" %}\n    {%- set system_message = messages[0][\"co"
    "ntent\"] %}\n    {%- set loop_messages = messages[1:] %}\n{%- else %}\n    {%- set loop_mess"
    "ages = messages %}\n{%- endif %}\n{%- if not tools is defined %}\n    {%- set tools = none %"
    "}\n{%- endif %}\n{%- set user_messages = loop_messages | selectattr(\"role\", \"equalto\", "
    "\"user\") | list %}\n\n{#- This block checks for alternating user/assistant messages, skippi"
    "ng tool calling messages #}\n{%- set ns = namespace() %}\n{%- set ns.index = 0 %}\n{%- for m"
    "essage in loop_messages %}\n    {%- if not (message.role == \"tool\" or message.role == \"to"
    "ol_results\" or (message.tool_calls is defined and message.tool_calls is not none)) %}\n    "
    "    {%- if (message[\"role\"] == \"user\") != (ns.index % 2 == 0) %}\n            {{- raise_"
    "exception(\"After the optional system message, conversation roles must alternate user/assist"
    "ant/user/assistant/...\") }}\n        {%- endif %}\n        {%- set ns.index = ns.index + 1 "
    "%}\n    {%- endif %}\n{%- endfor %}\n\n{{- bos_token }}\n{%- for message in loop_messages %}"
    "\n    {%- if message[\"role\"] == \"user\" %}\n        {%- if tools is not none and (message"
    " == user_messages[-1]) %}\n            {{- \"[AVAILABLE_TOOLS] [\" }}\n            {%- for t"
    "ool in tools %}\n                {%- set tool = tool.function %}\n                {{- '{\"ty"
    "pe\": \"function\", \"function\": {' }}\n                {%- for key, val in tool.items() if"
    " key != \"return\" %}\n                    {%- if val is string %}\n                        "
    "{{- '\"' + key + '\": \"' + val + '\"' }}\n                    {%- else %}\n                "
    "        {{- '\"' + key + '\": ' + val|tojson }}\n                    {%- endif %}\n         "
    "           {%- if not loop.last %}\n                        {{- \", \" }}\n                 "
    "   {%- endif %}\n                {%- endfor %}\n                {{- \"}}\" }}\n             "
    "   {%- if not loop.last %}\n                    {{- \", \" }}\n                {%- else %}\n"
    "                    {{- \"]\" }}\n                {%- endif %}\n            {%- endfor %}\n "
    "           {{- \"[/AVAILABLE_TOOLS]\" }}\n            {%- endif %}\n        {%- if loop.last"
    " and system_message is defined %}\n            {{- \"[INST] \" + system_message + \"\\n\\n\""
    " + message[\"content\"] + \"[/INST]\" }}\n        {%- else %}\n            {{- \"[INST] \" +"
    " message[\"content\"] + \"[/INST]\" }}\n        {%- endif %}\n    {%- elif message.tool_call"
    "s is defined and message.tool_calls is not none %}\n        {{- \"[TOOL_CALLS] [\" }}\n     "
    "   {%- for tool_call in message.tool_calls %}\n            {%- set out = tool_call.function|"
    "tojson %}\n            {{- out[:-1] }}\n            {%- if not tool_call.id is defined or to"
    "ol_call.id|length != 9 %}\n                {{- raise_exception(\"Tool call IDs should be alp"
    "hanumeric strings with length 9!\") }}\n            {%- endif %}\n            {{- ', \"id\":"
    " \"' + tool_call.id + '\"}' }}\n            {%- if not loop.last %}\n                {{- \","
    " \" }}\n            {%- else %}\n                {{- \"]\" + eos_token }}\n            {%- e"
    "ndif %}\n        {%- endfor %}\n    {%- elif message[\"role\"] == \"assistant\" %}\n        "
    "{{- \" \" + message[\"content\"]|trim + eos_token}}\n    {%- elif message[\"role\"] == \"too"
    "l_results\" or message[\"role\"] == \"tool\" %}\n        {%- if message.content is defined a"
    "nd message.content.content is defined %}\n            {%- set content = message.content.cont"
    "ent %}\n        {%- else %}\n            {%- set content = message.content %}\n        {%- e"
    "ndif %}\n        {{- '[TOOL_RESULTS] {\"content\": ' + content|string + \", \" }}\n        {"
    "%- if not message.tool_call_id is defined or message.tool_call_id|length != 9 %}\n          "
    "  {{- raise_exception(\"Tool call IDs should be alphanumeric strings with length 9!\") }}\n "
    "       {%- endif %}\n        {{- '\"call_id\": \"' + message.tool_call_id + '\"}[/TOOL_RESUL"
    "TS]' }}\n    {%- else %}\n        {{- raise_exception(\"Only user and assistant roles are su"
    "pported, with the exception of an initial optional system message!\") }}\n    {%- endif %}\n"
    "{%- endfor %}\n"
    ;
inline const std::string k_mistral_v3_bos =
    "<s>"
    ;
inline const std::string k_mistral_v3_eos =
    "</s>"
    ;
inline const std::string k_mistral_v3_user_only =
    "<s>[INST] What is the capital of France?[/INST]"
    ;
inline const std::string k_mistral_v3_system_user =
    "<s>[INST] You are a terse assistant.\n\nHello there.[/INST]"
    ;
inline const std::string k_mistral_v3_multi_turn =
    "<s>[INST] Hi[/INST] Hello! How can I help?</s>[INST] What is 2+2?[/INST]"
    ;

// nemotron  <-  nvidia/Nemotron-4-Mini-Hindi-4B-Instruct  (detected family: NEMOTRON)
inline const std::string k_nemotron_template =
    "{%- if messages[0]['role'] == 'system' -%}{%- set system_message = messages[0]['content'] | "
    "trim -%}{%- set messages = messages[1:] -%}{%- else -%}{%- set system_message = '' -%}{%- en"
    "dif -%}{%- if tools -%}{{- '<extra_id_0>System' + '\n' + system_message -}}{{- '\n' if syste"
    "m_message else '' -}}{{- '<AVAILABLE_TOOLS>[' -}}{% for t in tools %}{{- (t.function if t.fu"
    "nction is defined else t) | tojson() -}}{{- ', ' if not loop.last else '' -}}{%- endfor -%}{"
    "{- ']</AVAILABLE_TOOLS>' -}}{{- '\n' -}}{%- else -%}{{- '<extra_id_0>System' + '\n' + system"
    "_message + '\n' -}}{%- endif -%}{%- for message in messages -%}{%- if (message['role'] in ['"
    "user', 'tool']) != (loop.index0 % 2 == 0) -%}{{- raise_exception('Conversation roles must al"
    "ternate between user/tool and assistant') -}}{%- elif message['role'] == 'user' -%}{{- '<ext"
    "ra_id_1>User' + '\n' + message['content'] | trim + '\n' -}}{%- elif message['role'] == 'tool"
    "' -%}{%- set tool_response = '<TOOL_RESPONSE>[' + message['content'] | trim + ']</TOOL_RESPO"
    "NSE>' -%}{{- '<extra_id_1>User' + '\n' + tool_response + '\n' -}}{%- elif message['role'] =="
    " 'assistant' and message.get('tool_calls') is not none -%}{%- set tool_calls = message['tool"
    "_calls'] -%}{{- '<extra_id_1>Assistant' + '\n' + '<TOOLCALL>[' -}}{%- for tool_call in tool_"
    "calls -%}{{ {\"name\": tool_call.function.name, \"arguments\": tool_call.function.arguments}"
    " | tojson }}{%- if not loop.last -%}{{ ', ' }}{%- else -%}{{ ']</TOOLCALL>' + '\n' }}{%- end"
    "if -%}{%- endfor -%}{%- elif message['role'] == 'assistant' -%}{{- '<extra_id_1>Assistant' +"
    " '\n' + message['content'] | trim + '\n' -}}{%- endif -%}{%- endfor -%}{%- if add_generation"
    "_prompt -%}{{ '<extra_id_1>Assistant' + '\n' }}{%- endif -%}"
    ;
inline const std::string k_nemotron_bos =
    "<s>"
    ;
inline const std::string k_nemotron_eos =
    "<extra_id_1>"
    ;
inline const std::string k_nemotron_user_only =
    "<extra_id_0>System\n\n<extra_id_1>User\nWhat is the capital of France?\n<extra_id_1>Assistan"
    "t\n"
    ;
inline const std::string k_nemotron_system_user =
    "<extra_id_0>System\nYou are a terse assistant.\n<extra_id_1>User\nHello there.\n<extra_id_1>"
    "Assistant\n"
    ;
inline const std::string k_nemotron_multi_turn =
    "<extra_id_0>System\n\n<extra_id_1>User\nHi\n<extra_id_1>Assistant\nHello! How can I help?\n<"
    "extra_id_1>User\nWhat is 2+2?\n<extra_id_1>Assistant\n"
    ;

// deepseek_r1  <-  deepseek-ai/DeepSeek-R1  (detected family: DEEPSEEK_R1)
inline const std::string k_deepseek_r1_template =
    "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif"
    " %}{% set ns = namespace(is_first=false, is_tool=false, is_output_first=true, system_prompt="
    "'', is_first_sp=true) %}{%- for message in messages %}{%- if message['role'] == 'system' %}{"
    "%- if ns.is_first_sp %}{% set ns.system_prompt = ns.system_prompt + message['content'] %}{% "
    "set ns.is_first_sp = false %}{%- else %}{% set ns.system_prompt = ns.system_prompt + '\\n\\n"
    "' + message['content'] %}{%- endif %}{%- endif %}{%- endfor %}{{ bos_token }}{{ ns.system_pr"
    "ompt }}{%- for message in messages %}{%- if message['role'] == 'user' %}{%- set ns.is_tool ="
    " false -%}{{'<｜User｜>' + message['content']}}{%- endif %}{%- if message['role'] == 'assistan"
    "t' and 'tool_calls' in message %}{%- set ns.is_tool = false -%}{%- for tool in message['tool"
    "_calls'] %}{%- if not ns.is_first %}{%- if message['content'] is none %}{{'<｜Assistant｜><｜to"
    "ol▁calls▁begin｜><｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['nam"
    "e'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁ca"
    "ll▁end｜>'}}{%- else %}{{'<｜Assistant｜>' + message['content'] + '<｜tool▁calls▁begin｜><｜tool▁c"
    "all▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' "
    "+ '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}{%- endif %}{"
    "%- set ns.is_first = true -%}{%- else %}{{'\\n' + '<｜tool▁call▁begin｜>' + tool['type'] + '<｜"
    "tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['argum"
    "ents'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}{%- endif %}{%- endfor %}{{'<｜tool▁calls▁end｜>"
    "<｜end▁of▁sentence｜>'}}{%- endif %}{%- if message['role'] == 'assistant' and 'tool_calls' not"
    " in message %}{%- if ns.is_tool %}{{'<｜tool▁outputs▁end｜>' + message['content'] + '<｜end▁of▁"
    "sentence｜>'}}{%- set ns.is_tool = false -%}{%- else %}{% set content = message['content'] %}"
    "{% if '</think>' in content %}{% set content = content.split('</think>')[-1] %}{% endif %}{{"
    "'<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>'}}{%- endif %}{%- endif %}{%- if message['r"
    "ole'] == 'tool' %}{%- set ns.is_tool = true -%}{%- if ns.is_output_first %}{{'<｜tool▁outputs"
    "▁begin｜><｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- set ns.is_o"
    "utput_first = false %}{%- else %}{{'<｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁ou"
    "tput▁end｜>'}}{%- endif %}{%- endif %}{%- endfor -%}{% if ns.is_tool %}{{'<｜tool▁outputs▁end｜"
    ">'}}{% endif %}{% if add_generation_prompt and not ns.is_tool %}{{'<｜Assistant｜><think>\\n'}"
    "}{% endif %}"
    ;
inline const std::string k_deepseek_r1_bos =
    "<｜begin▁of▁sentence｜>"
    ;
inline const std::string k_deepseek_r1_eos =
    "<｜end▁of▁sentence｜>"
    ;
inline const std::string k_deepseek_r1_user_only =
    "<｜begin▁of▁sentence｜><｜User｜>What is the capital of France?<｜Assistant｜><think>\n"
    ;
inline const std::string k_deepseek_r1_system_user =
    "<｜begin▁of▁sentence｜>You are a terse assistant.<｜User｜>Hello there.<｜Assistant｜><think>\n"
    ;
inline const std::string k_deepseek_r1_multi_turn =
    "<｜begin▁of▁sentence｜><｜User｜>Hi<｜Assistant｜>Hello! How can I help?<｜end▁of▁sentence｜><｜User｜"
    ">What is 2+2?<｜Assistant｜><think>\n"
    ;

// phi  <-  microsoft/Phi-3-mini-4k-instruct  (detected family: PHI)
inline const std::string k_phi_template =
    "{% for message in messages %}{% if message['role'] == 'system' %}{{'<|system|>\n' + message["
    "'content'] + '<|end|>\n'}}{% elif message['role'] == 'user' %}{{'<|user|>\n' + message['cont"
    "ent'] + '<|end|>\n'}}{% elif message['role'] == 'assistant' %}{{'<|assistant|>\n' + message["
    "'content'] + '<|end|>\n'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<|assista"
    "nt|>\n' }}{% else %}{{ eos_token }}{% endif %}"
    ;
inline const std::string k_phi_bos =
    "<s>"
    ;
inline const std::string k_phi_eos =
    "<|endoftext|>"
    ;
inline const std::string k_phi_user_only =
    "<|user|>\nWhat is the capital of France?<|end|>\n<|assistant|>\n"
    ;
inline const std::string k_phi_system_user =
    "<|system|>\nYou are a terse assistant.<|end|>\n<|user|>\nHello there.<|end|>\n<|assistant|>"
    "\n"
    ;
inline const std::string k_phi_multi_turn =
    "<|user|>\nHi<|end|>\n<|assistant|>\nHello! How can I help?<|end|>\n<|user|>\nWhat is 2+2?<|e"
    "nd|>\n<|assistant|>\n"
    ;

}  // namespace chat_goldens
