#!/usr/bin/env python3
"""Generate fp64 spot-check goldens for tests/test_attention_crosspath.cu.

The C++ test generates Q/K/V with the IDENTICAL integer-LCG + f32
multiply-only recipe below (bit-exact across numpy/C++ — no libm calls),
computes its own fp64 attention reference, and asserts 64 spot values per
config against this golden at 1e-9 rel. That proves the in-test reference
implements the same math as this independent numpy implementation; the GPU
paths are then judged against the verified reference.

Data recipe (realistic, heavy-tailed — mimics QK-normed activations):
  x_{n+1} = x_n * 1664525 + 1013904223          (uint32 LCG, per-tensor seed)
  v   = ((x >> 8) & 0x3FFF) - 8192              in [-8192, 8191]
  f   = v / 8192.0f                             uniform [-1, 1]  (f32)
  val = f*f*f * amp                             cubed -> heavy tails (f32)
  if (x & 0xFF) == 0: val *= 2.0f               1/256 outliers (to ~±16 @ amp=8;
                                                observed QK-normed spikes ~±10)
  stored as f16 (round-to-nearest-even); reference computed FROM the f16 bits.

Regenerate (host stays clean — run in a container with numpy):
  docker run --rm -v $PWD:/work -w /work python:3.12-slim \
    sh -c "pip install -q numpy && python3 tests/refs/gen_attention_crosspath_golden.py"
"""

import numpy as np

OUT = "tests/refs/attention_crosspath_golden.h"
N_SPOTS = 64

# (name, Sq, Skv, NH, NKV, HD, causal, sliding_window, softcap, amp)
#
# Two tiers (see tests/test_attention_crosspath.cu):
#   amp=2 "mild": score sigma ~0.6, softmax moderately diffuse — every path
#     must hold its class tolerance; catches layout/indexing/routing bugs.
#   amp=8 "sharp": score sigma ~9, near-one-hot softmax — only the f32-score
#     paths (cuBLAS FP32-S, FA2-f16) are held strict; fp8-QK and f16-accum
#     paths structurally cannot reproduce sharp attention on uncorrelated
#     data (measured: 17-76% of elements off) and are characterized instead.
CONFIGS = [
    ("mild_long_gqa", 192, 192, 4, 2, 128, True, 0, 0.0, 2.0),
    ("mild_short_gqa32", 24, 24, 32, 8, 128, True, 0, 0.0, 2.0),
    ("mild_sliding_softcap", 160, 160, 4, 4, 128, True, 64, 50.0, 2.0),
    ("sharp_long_gqa", 192, 192, 4, 2, 128, True, 0, 0.0, 8.0),
]


def lcg_fill(seed: int, n: int, amp: float) -> np.ndarray:
    """Bit-exact mirror of the C++ generator (f32 ops only, then f16)."""
    x = np.uint32(seed)
    out = np.empty(n, dtype=np.float16)
    one = np.float32(1.0 / 8192.0)
    amp32 = np.float32(amp)
    two = np.float32(2.0)
    for i in range(n):
        x = np.uint32((np.uint64(x) * 1664525 + 1013904223) & 0xFFFFFFFF)
        v = np.int32((x >> np.uint32(8)) & np.uint32(0x3FFF)) - np.int32(8192)
        f = np.float32(v) * one
        val = f * f * f * amp32
        if (x & np.uint32(0xFF)) == 0:
            val = val * two
        out[i] = np.float16(val)
    return out


def ref_attention(Qh, Kh, Vh, Sq, Skv, NH, NKV, HD, causal, sw, softcap):
    """fp64 reference from the f16-rounded inputs."""
    Q = Qh.astype(np.float64).reshape(Sq, NH, HD)
    K = Kh.astype(np.float64).reshape(Skv, NKV, HD)
    V = Vh.astype(np.float64).reshape(Skv, NKV, HD)
    scale = 1.0 / np.sqrt(float(HD))
    gqa = NH // NKV
    O = np.zeros((Sq, NH, HD), dtype=np.float64)
    for h in range(NH):
        kvh = h // gqa
        S = (Q[:, h, :] @ K[:, kvh, :].T) * scale  # [Sq, Skv]
        if softcap > 0.0:
            S = softcap * np.tanh(S / softcap)
        for i in range(Sq):
            for j in range(Skv):
                if causal and j > i:
                    S[i, j] = -np.inf
                elif sw > 0 and (i - j) >= sw:
                    S[i, j] = -np.inf
        m = S.max(axis=1, keepdims=True)
        P = np.exp(S - m)
        P /= P.sum(axis=1, keepdims=True)
        O[:, h, :] = P @ V[:, kvh, :]
    return O.reshape(-1)


def spot_indices(total: int) -> list:
    return [int((np.uint64(k) * np.uint64(2654435761)) % np.uint64(total)) for k in range(N_SPOTS)]


def main():
    lines = [
        "// AUTO-GENERATED by tests/refs/gen_attention_crosspath_golden.py — do not edit.",
        f"// numpy {np.__version__}; fp64 spot references for the attention cross-path test.",
        "// Regenerating must reproduce this file (see tests/refs/README.md).",
        "#pragma once",
        "",
        "namespace imp_refs {",
        "",
    ]
    for idx, (name, Sq, Skv, NH, NKV, HD, causal, sw, softcap, amp) in enumerate(CONFIGS):
        Qh = lcg_fill(0x1234 + idx * 3, Sq * NH * HD, amp)
        Kh = lcg_fill(0x5678 + idx * 3, Skv * NKV * HD, amp)
        Vh = lcg_fill(0x9ABC + idx * 3, Skv * NKV * HD, 1.0)  # V is not QK-normed
        O = ref_attention(Qh, Kh, Vh, Sq, Skv, NH, NKV, HD, causal, sw, softcap)
        idxs = spot_indices(O.size)
        lines.append(f"// config {name}: Sq={Sq} Skv={Skv} NH={NH} NKV={NKV} HD={HD} "
                     f"causal={int(causal)} sw={sw} softcap={softcap} amp={amp}")
        lines.append(f"inline constexpr int {name}_spot_idx[{N_SPOTS}] = {{")
        lines.append("    " + ", ".join(str(i) for i in idxs) + "};")
        lines.append(f"inline constexpr double {name}_spot_val[{N_SPOTS}] = {{")
        vals = ", ".join(f"{O[i]:.17g}" for i in idxs)
        lines.append("    " + vals + "};")
        lines.append("")
    lines.append("}  // namespace imp_refs")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
