#!/usr/bin/env python3
"""Generate the tokenizer parity golden from HuggingFace transformers.

    python3 tests/refs/gen_tokenizer_golden.py <model_dir> <out.h> [namespace]

`namespace` defaults to tokenizer_golden. Pass a distinct one when a second
model's golden has to link alongside the first: two headers both declaring
tokenizer_golden::k_model in one test binary is a redefinition, and the
tokenizers are genuinely different (Qwen3 is 151k, Qwen3.8 is 248k).

The output is a committed C++ header, not a JSON file read at run time
(#1569): the previous generator wrote JSON that nothing committed and the
test parsed with a substring scan, which truncated the one case containing a
'}' inside a string and silently dropped it (#1570). A header has neither
problem - the compiler parses it, and a missing golden is a build error
rather than a skip.

The corpus deliberately over-samples runs of whitespace: that is the defect
class of #657 (gemma-3 SPM USER_DEFINED literal-space pieces decomposing into
N single-space tokens, +37.5% NLL), and it is what a percentage-based
threshold used to let through.

Requires: transformers. The vllm image on this host already carries it:

    docker run --rm --entrypoint python3 \\
      -v $HOME/models:/models:ro -v $PWD:/src vllm/vllm-openai:v0.27.1 \\
      /src/tests/refs/gen_tokenizer_golden.py /models/Qwen3-0.6B \\
      /src/tests/refs/tokenizer_golden_qwen3.h
"""
import json
import sys

from transformers import AutoTokenizer

TEST_STRINGS = [
    "Hello, world!",
    "The quick brown fox jumps over the lazy dog.",
    "  Leading spaces",
    "Multiple   spaces   between",
    "12345 numbers 67890",
    "Special chars: !@#$%^&*()",
    "Unicode: café résumé naïve",
    "CJK: 你好世界",
    "Emoji: 🎉🚀",
    "Code: def foo(x):\n    return x + 1",
    "Mixed: Hello 你好 🌍 café 123",
    "Empty after trim:   ",
    "Newlines\n\nand\ttabs",
    "Contractions: I'm don't won't can't",
    "URL: https://example.com/path?q=hello&lang=en",
    "JSON: {\"key\": \"value\", \"num\": 42}",
    "",
    " ",
    "a",
    "A" * 100,
    # Whitespace runs, the #657 class.
    "        eight leading spaces",
    "trailing spaces        ",
    "tab\tseparated\tfields",
    "\t\t\tthree leading tabs",
    "mixed \t \t whitespace \t run",
    "line1\r\nline2\r\nline3",
    "para\n\n\n\nbreak",
    "  \n  indent after newline",
    # Chat-control literals appearing as ordinary text: the tokenizer
    # pre-splits on its special pieces, so this is where imp and HF can
    # disagree without any ordinary string showing it.
    "<|im_start|>user",
    "text <|endoftext|> text",
    # Digit grouping and long runs.
    "1234567890123456789012345678901234567890",
    "0.000001 and 1e-9 and -42",
]


def c_escape(s: str) -> str:
    out = []
    for b in s.encode("utf-8"):
        c = chr(b)
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif c == "\n":
            out.append("\\n")
        elif c == "\r":
            out.append("\\r")
        elif c == "\t":
            out.append("\\t")
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            out.append("\\x%02x\"\"" % b)  # split so a following hex digit cannot extend the escape
    return "".join(out)


def main() -> int:
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <model_dir> <out.h>")
        return 1
    model_path, out_path = sys.argv[1], sys.argv[2]
    ns = sys.argv[3] if len(sys.argv) > 3 else "tokenizer_golden"

    tok = AutoTokenizer.from_pretrained(model_path)
    cases = []
    for text in TEST_STRINGS:
        ids = tok.encode(text, add_special_tokens=False)
        cases.append((text, ids, tok.decode(ids)))

    name = model_path.rstrip("/").split("/")[-1]
    lines = [
        "// GENERATED by tests/refs/gen_tokenizer_golden.py - do not edit.",
        "//",
        f"// Reference: transformers AutoTokenizer.from_pretrained({name!r}),",
        "// encode(add_special_tokens=False) and decode() over the corpus in the",
        "// generator. The test refuses a model whose fingerprint differs rather",
        "// than comparing against the wrong reference (#1569, #1570).",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <string>",
        "#include <vector>",
        "",
        f"namespace {ns} {{",
        "",
        "struct Case {",
        "    const char* text;",
        "    std::vector<int32_t> ids;",
        "    const char* decoded;",
        "};",
        "",
        f'inline constexpr const char* k_model = "{name}";',
        f"inline constexpr int k_vocab_size = {tok.vocab_size};",
        f"inline constexpr int k_n_tokens = {len(tok)};",
        "",
        "// Fingerprint: if a model tokenizes this differently it is not the",
        "// tokenizer this golden describes, and the comparison would be noise.",
        f'inline constexpr const char* k_fingerprint_text = "{c_escape(TEST_STRINGS[0])}";',
        "inline const std::vector<int32_t> k_fingerprint_ids = {"
        + ", ".join(str(i) for i in cases[0][1])
        + "};",
        "",
        "inline const std::vector<Case>& cases() {",
        "    static const std::vector<Case> v = {",
    ]
    for text, ids, decoded in cases:
        lines.append(
            '        {"%s", {%s}, "%s"},'
            % (c_escape(text), ", ".join(str(i) for i in ids), c_escape(decoded))
        )
    lines += [
        "    };",
        "    return v;",
        "}",
        "",
        f"}}  // namespace {ns}",
        "",
    ]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"{len(cases)} cases -> {out_path}  (vocab_size={tok.vocab_size}, n_tokens={len(tok)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
