#!/usr/bin/env python3
"""Generate fp64 spot-check goldens for tests/test_gpt_oss_yarn_ref.cu.

Independent YaRN-scaled RoPE reference (numpy fp64), derived from the YaRN
paper / HF GptOssRotaryEmbedding semantics — NOT from imp. The C++ test
reimplements the SAME math in fp64 and asserts its spot values against this
golden at 1e-9 rel (proving the two implementations agree), then judges the
GPU rope kernel against the verified fp64 reference at the f16 tolerance.

The point of the test is the rope_freq_scale-INVERSION bug class (#547): the
HF config gives a YaRN `factor` (e.g. 32). imp stores the factor and the
kernel applies 1/factor. Storing 1/factor instead double-inverts -> the
interpolated dims rotate factor^2 = 1024x too fast and the mscale flips sign.
This golden pins the rotated Q/K at LARGE positions (beyond original ctx),
where that error is enormous, so the test cannot pass with the wrong scale.

gpt-oss-20b YaRN params (config.json):
  head_dim=64, rope_theta=150000, factor=32, beta_fast=32, beta_slow=1,
  original_max_position_embeddings=4096, max_position_embeddings=131072.

Regenerate (host stays clean — run in a container with numpy):
  docker run --rm -v $PWD:/work -w /work python:3.12-slim \
    sh -c "pip install -q numpy && python3 tests/refs/gen_yarn_rope_golden.py"
"""

import numpy as np

OUT = "tests/refs/yarn_rope_golden.h"

# gpt-oss-20b
HEAD_DIM = 64
THETA = 150000.0
FACTOR = 32.0
BETA_FAST = 32.0
BETA_SLOW = 1.0
N_CTX_ORIG = 4096
# Positions sampled across the range incl. the original-ctx boundary and deep
# into the YaRN-extended region (131072 max). 100k+ is where a 1024x freq
# error produces an angle blow-up of millions of radians.
POSITIONS = [0, 1, 4095, 4096, 8192, 32768, 100000, 131071]


def yarn_corr_dim(n_dims, n_ctx_orig, n_rot, base):
    # llama.cpp rope_yarn_corr_dim / imp rope_yarn_corr_dim_impl
    return n_dims * np.log(n_ctx_orig / (n_rot * 2.0 * np.pi)) / (2.0 * np.log(base))


def yarn_corr_dims(n_dims, n_ctx_orig, base, beta_fast, beta_slow):
    start = np.floor(yarn_corr_dim(n_dims, n_ctx_orig, beta_fast, base))
    end = np.ceil(yarn_corr_dim(n_dims, n_ctx_orig, beta_slow, base))
    return max(0.0, start), min(n_dims - 1.0, end)


def yarn_ramp(low, high, i0):
    # imp rope_yarn_ramp(low, high, i0): i0 is 2*pair_idx
    y = (i0 / 2.0 - low) / max(0.001, high - low)
    return 1.0 - min(1.0, max(0.0, y))


def rope_yarn_cos_sin(pos, pair_idx, n_pairs, theta, factor, cd0, cd1):
    """Mirror imp's rope_yarn device helper, fp64.

    inv_scaling = 1/factor (the kernel inverts the stored factor).
    theta_extrap = pos / theta^((2*pair)/(2*n_pairs))
    theta_interp = inv_scaling * theta_extrap
    ramp_mix = ramp(cd0,cd1, 2*pair) * ext_factor(=1)
    theta = interp*(1-ramp_mix) + extrap*ramp_mix
    mscale = attn_factor(=1) * (1 + 0.1*ln(1/inv_scaling)) = 1 + 0.1*ln(factor)
    """
    inv_scaling = 1.0 / factor
    theta_extrap = pos / (theta ** ((2.0 * pair_idx) / (2.0 * n_pairs)))
    theta_interp = inv_scaling * theta_extrap
    ramp_mix = yarn_ramp(cd0, cd1, 2 * pair_idx) * 1.0
    th = theta_interp * (1.0 - ramp_mix) + theta_extrap * ramp_mix
    mscale = 1.0 + 0.1 * np.log(1.0 / inv_scaling)
    return np.cos(th) * mscale, np.sin(th) * mscale


def main():
    n_pairs = HEAD_DIM // 2
    cd0, cd1 = yarn_corr_dims(HEAD_DIM, N_CTX_ORIG, THETA, BETA_FAST, BETA_SLOW)

    rows = []  # (pos, pair, cos, sin)
    for pos in POSITIONS:
        for pair in range(n_pairs):
            c, s = rope_yarn_cos_sin(pos, pair, n_pairs, THETA, FACTOR, cd0, cd1)
            rows.append((pos, pair, c, s))

    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tests/refs/gen_yarn_rope_golden.py — DO NOT EDIT.\n")
        f.write("// Independent fp64 YaRN-RoPE reference (numpy) for gpt-oss-20b params.\n")
        f.write("// tool: python3 + numpy %s ; date 2026-06-06\n" % np.__version__)
        f.write("// head_dim=%d theta=%.1f factor=%.1f beta_fast=%.1f beta_slow=%.1f n_ctx_orig=%d\n"
                % (HEAD_DIM, THETA, FACTOR, BETA_FAST, BETA_SLOW, N_CTX_ORIG))
        f.write("#pragma once\n#include <cstdint>\nnamespace imp {\nnamespace yarn_golden {\n")
        f.write("constexpr int kHeadDim = %d;\n" % HEAD_DIM)
        f.write("constexpr double kTheta = %.10g;\n" % THETA)
        f.write("constexpr double kFactor = %.10g;\n" % FACTOR)
        f.write("constexpr double kBetaFast = %.10g;\n" % BETA_FAST)
        f.write("constexpr double kBetaSlow = %.10g;\n" % BETA_SLOW)
        f.write("constexpr int kNCtxOrig = %d;\n" % N_CTX_ORIG)
        f.write("constexpr double kCorrDim0 = %.17g;\n" % cd0)
        f.write("constexpr double kCorrDim1 = %.17g;\n" % cd1)
        f.write("constexpr int kNumPositions = %d;\n" % len(POSITIONS))
        f.write("constexpr int kPositions[%d] = {%s};\n"
                % (len(POSITIONS), ", ".join(str(p) for p in POSITIONS)))
        f.write("constexpr int kNumRows = %d;\n" % len(rows))
        f.write("struct YarnRow { int pos; int pair; double cos; double sin; };\n")
        f.write("constexpr YarnRow kRows[%d] = {\n" % len(rows))
        for (pos, pair, c, s) in rows:
            f.write("  {%d, %d, %.17g, %.17g},\n" % (pos, pair, c, s))
        f.write("};\n}  // namespace yarn_golden\n}  // namespace imp\n")
    print("wrote", OUT, "rows=", len(rows), "corr_dims=", (cd0, cd1))


if __name__ == "__main__":
    main()
