#!/usr/bin/env python3
"""Generate Harmony chat-template golden render strings for gpt-oss-20b.

Independent ground truth from the REAL HF reference: loads the gpt-oss-20b
tokenizer's chat template via `transformers.AutoTokenizer` and renders fixed
conversations with `apply_chat_template(tokenize=False)`. The C++ test
(tests/test_gpt_oss_harmony_golden.cpp) renders the SAME committed
chat_template.jinja through imp's jinja engine and compares the string
exactly. Any divergence is either a jinja-engine gap or a real parity bug.

This only needs the tokenizer config + chat_template.jinja (tiny), NOT the
weights. It reads them from the local model dir if present, else downloads
just the tokenizer from the Hub.

Regenerate (host stays clean — run in a container with transformers):
  docker run --rm -v $PWD:/work -v $HOME/models:/models -w /work \\
    python:3.12-slim sh -c \\
    "pip install -q transformers jinja2 && \\
     MODEL=/models/gpt-oss-20b python3 tests/refs/gen_harmony_golden.py"

If /models is unavailable, omit -v and the MODEL env to fetch from the Hub
(MODEL defaults to openai/gpt-oss-20b).
"""

import json
import os

from transformers import AutoTokenizer

MODEL = os.environ.get("MODEL", "openai/gpt-oss-20b")
OUT = "tests/refs/harmony_golden.h"

# Fixed conversations. Names map 1:1 to the C++ test cases. Kept simple
# (no tools — imp's harmony rendering path is messages-only) to isolate the
# channel/role markers the parity test cares about.
CONVERSATIONS = {
    "user_only": [
        {"role": "user", "content": "What is the capital of France?"},
    ],
    "system_user": [
        {"role": "system", "content": "You are a terse assistant."},
        {"role": "user", "content": "Hello there."},
    ],
    "multi_turn": [
        {"role": "user", "content": "Hi"},
        {"role": "assistant", "content": "Hello! How can I help?"},
        {"role": "user", "content": "What is 2+2?"},
    ],
}


def esc(s: str) -> str:
    """C++ raw-string-safe escaping: emit as a normal escaped string literal."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def main():
    tok = AutoTokenizer.from_pretrained(MODEL)
    print("loaded tokenizer:", MODEL)

    renders = {}
    for name, msgs in CONVERSATIONS.items():
        # add_generation_prompt=True: the prompt the model continues from.
        rendered = tok.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True
        )
        renders[name] = rendered
        print("=== %s (%d chars) ===" % (name, len(rendered)))

    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tests/refs/gen_harmony_golden.py — DO NOT EDIT.\n")
        f.write("// Harmony chat-template golden render strings from the REAL HF\n")
        f.write("// reference (transformers AutoTokenizer.apply_chat_template).\n")
        f.write("// model: %s ; transformers chat_template.jinja ; date 2026-06-06\n" % MODEL)
        f.write("#pragma once\n#include <string>\nnamespace imp {\nnamespace harmony_golden {\n")
        for name, rendered in renders.items():
            f.write('inline const std::string k_%s =\n    "%s";\n' % (name, esc(rendered)))
        f.write("}  // namespace harmony_golden\n}  // namespace imp\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
