// AUTO-GENERATED by tests/refs/gen_harmony_golden.py — DO NOT EDIT.
// Harmony chat-template golden render strings from the REAL HF
// reference (transformers AutoTokenizer.apply_chat_template).
// model: /models/gpt-oss-20b ; transformers chat_template.jinja ; date 2026-06-06
#pragma once
#include <string>
namespace imp {
namespace harmony_golden {
inline const std::string k_user_only =
    "<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2024-06\nCurrent date: 2026-06-06\n\nReasoning: medium\n\n# Valid channels: analysis, commentary, final. Channel must be included for every message.<|end|><|start|>user<|message|>What is the capital of France?<|end|><|start|>assistant";
inline const std::string k_system_user =
    "<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2024-06\nCurrent date: 2026-06-06\n\nReasoning: medium\n\n# Valid channels: analysis, commentary, final. Channel must be included for every message.<|end|><|start|>developer<|message|># Instructions\n\nYou are a terse assistant.\n\n<|end|><|start|>user<|message|>Hello there.<|end|><|start|>assistant";
inline const std::string k_multi_turn =
    "<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2024-06\nCurrent date: 2026-06-06\n\nReasoning: medium\n\n# Valid channels: analysis, commentary, final. Channel must be included for every message.<|end|><|start|>user<|message|>Hi<|end|><|start|>assistant<|channel|>final<|message|>Hello! How can I help?<|end|><|start|>user<|message|>What is 2+2?<|end|><|start|>assistant";
}  // namespace harmony_golden
}  // namespace imp
