#include "usage.h"

#include <cstdio>

void usage() {
    printf(
        "usage: imp-quantize --model <safetensors-dir> --out <dir> [--calib <file>]\n"
        "                    [--format modelopt|vllm] [--lm-head] [--dry-run]\n"
        "\n"
        "  --model DIR   source checkpoint (BF16/FP16 SafeTensors + config.json)\n"
        "  --out DIR     destination; created if missing\n"
        "  --format F    output layout (default modelopt):\n"
        "                  modelopt            .weight / .weight_scale_2, declared in\n"
        "                                      hf_quant_config.json. imp reads it.\n"
        "                  vllm                compressed-tensors nvfp4-pack-quantized:\n"
        "                  (= compressed-tensors)  .weight_packed / .weight_global_scale,\n"
        "                                      declared in config.json. imp AND vLLM read\n"
        "                                      it, and fused layers (q/k/v, gate/up) share\n"
        "                                      one tensor scale, which vLLM requires.\n"
        "  --calib FILE  activation calibration (AWQ scaling). Produce it with:\n"
        "                  imp-cli --model DIR --perplexity <corpus> --calibrate FILE\n"
        "                Without it the quantization is plain round-to-nearest,\n"
        "                which costs measurably more quality (see the header).\n"
        "  --calib-groups ABCDEG\n"
        "  --calib-weight abs|sq  error weight of the AWQ search (default abs)\n"
        "                Which AWQ scale groups run (default ABCDEG).\n"
        "                  A q,k,v  <- input_layernorm        C o_proj   <- v_proj\n"
        "                  B gate,up<- post_attention_norm    D down_proj<- up_proj\n"
        "                  G linear_attn.in_proj_* <- input_layernorm   (qwen3_5 GDN)\n"
        "                  E linear_attn.out_proj  <- linear_attn.norm  (qwen3_5 GDN)\n"
        "                E and G exist only on the GDN hybrids and are NOT measured\n"
        "                against an uncalibrated twin yet.\n"
        "                The ATTENTION groups (A, C) are what breaks on wide GQA:\n"
        "                on Qwen3-14B (n_rep=5) ABCD costs +2.68 PPL while BD --\n"
        "                the two FFN groups -- GAINS 0.13 over round-to-nearest.\n"
        "                Use 'BD' on wide-GQA models, the default on narrow ones,\n"
        "                or any subset to attribute a bad result. See\n"
        "                docs/quantization.md.\n"
        "  --lm-head     also quantize lm_head (default: excluded, imp applies its\n"
        "                own measured lm_head policy at runtime)\n"
        "  --keep-attn-gate\n"
        "                keep a fused Q+gate q_proj (Qwen3.5 / Qwen3-Next\n"
        "                `attn_output_gate`) out of NVFP4. OFF by default: the gate\n"
        "                half carries #1273's divergence, but excluding it measured\n"
        "                ~1.5%% WORSE on perplexity, not better, and costs 1-4%% of\n"
        "                the checkpoint. Kept for models with a higher gate share.\n"
        "  --keep-gdn-proj [all|in,gate,out]\n"
        "                keep GDN linear_attn projections at source precision: in =\n"
        "                in_proj_qkv(+a/b), gate = in_proj_z, out = out_proj; bare flag\n"
        "                = all, the Qwen3.6-35B-A3B-NVFP4 recipe. The runtime runs them\n"
        "                through its F16 GDN path (FP8 decode sidecar, opt-in NVFP4\n"
        "                prefill copies). Qwen3.8-27B: all = 10.6 GiB BF16 and the\n"
        "                checkpoint no longer fits 32 GB; in = 5 GiB fits.\n"
        "  --dry-run    report what would be quantized and how large the result\n"
        "                will be, against what the card has left. Writes nothing.\n");
}
