#!/usr/bin/env bash
# scripts/check-release.sh — pre-release sanity gate.
#
# Runs the cheap checks that should always pass on a publishable
# tree: doc links, secrets/path leaks, no accidentally tracked
# binaries, then defers to `make verify-fast` for build + test
# + perf + smoke and to `make test-server` for the HTTP surface.
#
# Both model-backed stages are needed and neither substitutes for the other:
# verify-fast measures kernels and throughput, test-server is the ONLY place
# handlers.cpp and batching_engine run end to end (Makefile, test-server).
# A defect that only shows over HTTP passes verify-fast untouched — one did:
# `response_format: json_schema` returned invalid JSON for months and this gate
# reported OK every time, because it never asked the server anything.
#
# SKIP_VERIFY=1 skips BOTH of them. The summary then refuses the words "all
# gates passed" and says what it actually checked, because a run that put no
# model in front of the GPU is a statement about the tree, not a release
# verdict — the rule #1474 put into scripts/verify.sh, for the same reason.
#
# It still exits 0 in that mode, deliberately: the `Release hygiene` CI job
# runs exactly this way (ci.yml, SKIP_VERIFY: "1") because the runner has no
# GPU, and a job that can never be green teaches people to ignore it. The
# distinction is carried by the summary line, which is what a human reads
# before tagging — not by an exit code that would only break CI.
#
# Exit code 0 if everything passes; non-zero otherwise.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

RED=$(tput setaf 1 || echo)
GRN=$(tput setaf 2 || echo)
YLW=$(tput setaf 3 || echo)
RST=$(tput sgr0 || echo)

FAIL=0
# Model-backed stages that actually put a checkpoint in front of the GPU.
# SKIP_VERIFY=1 leaves this at zero, and the summary refuses to report success
# while it is — see the header.
MODEL_STAGES_RUN=0
section() { echo; echo "${YLW}== $* ==${RST}"; }
pass()    { echo "${GRN}PASS${RST} $*"; }
fail()    { echo "${RED}FAIL${RST} $*"; FAIL=$((FAIL+1)); }

# ---------------------------------------------------------------- 1. doc links
# Every (./*.md or docs/*.md) link of the form ](path) — where path looks
# like a relative file — must resolve to a tracked file.
section "doc links"
# Resolve each link against the file that CONTAINS it, which is the only
# correct answer. The previous version deduplicated targets globally and then
# guessed a prefix from a fixed list (repo root, docs/, docs/audit/); adding
# docs/internals/ broke every sibling link inside it, and the next new
# subdirectory would have broken again.
BROKEN=0
while IFS= read -r docfile; do
    [ -z "$docfile" ] && continue
    dir=$(dirname "$docfile")
    while IFS= read -r link; do
        [ -z "$link" ] && continue
        case "$link" in http*|https*|mailto:*) continue ;; esac
        [ -e "$dir/$link" ] || { echo "  broken: $docfile -> $link"; BROKEN=$((BROKEN+1)); }
    done < <(grep -Eho '\]\(([^)# ]+\.(md|example|json|sh|cmake|h|cpp|cu))\)' "$docfile" 2>/dev/null \
             | sed -E 's/^\]\(//; s/\)$//' | sort -u)
done < <(git ls-files -- 'README.md' 'CONTRIBUTING.md' 'CHANGELOG.md' 'docs/**/*.md' 'docs/*.md')
[ "$BROKEN" -eq 0 ] && pass "all internal doc links resolve" \
                   || fail "$BROKEN broken internal doc link(s)"

# ------------------------------------------------- 1b. doc pointers in code
# A "see docs/<name>.md" in a comment is a promise the file is there. Sixteen
# design memos were deleted in doc-consolidation PRs (#183, #273, #441) and the
# ~38 pointers to them stayed behind in kernel comments, so following one led
# nowhere for two months. Section 1 covers markdown links; this covers code and
# scripts. Allowlisted: paths a tool WRITES rather than reads.
section "doc pointers in code"
DOC_ALLOW="docs/gemma4_layer_diff.md"   # generated by tools/analysis/layer_diff.py --out-md
DOCREFS=$(git ls-files -- '*.sh' '*.py' '*.cpp' '*.cu' '*.h' '*.hpp' '*.toml' '*.cmake' 'CMakeLists.txt' \
          | xargs grep -ohE '\bdocs/[A-Za-z0-9_./-]+\.md\b' 2>/dev/null | sort -u || true)
DOCBROKEN=0
while IFS= read -r ref; do
    [ -z "$ref" ] && continue
    case " $DOC_ALLOW " in *" $ref "*) continue ;; esac
    if [ ! -e "$ref" ]; then
        echo "  dead pointer: $ref"
        DOCBROKEN=$((DOCBROKEN+1))
    fi
done <<< "$DOCREFS"
[ "$DOCBROKEN" -eq 0 ] && pass "every docs/*.md path named in code resolves" \
                      || fail "$DOCBROKEN dead doc pointer(s) in code"

# ---------------------------------------------------- 1c. settled-prior anchors
# docs/audit/SETTLED.md is the ledger an audit reads BEFORE generating
# hypotheses; each entry names the file that makes it settled. If that anchor
# stops resolving, the entry is no longer a statement about this engine — it is
# the next stale prior, which is exactly what cost the 2026-07-29 audit eight of
# its thirteen hypotheses. Fail loudly so the entry gets re-opened rather than
# silently repointed. Same shape as 1b, different corpus.
section "settled-prior anchors"
if [ ! -e docs/audit/SETTLED.md ]; then
    fail "docs/audit/SETTLED.md is missing — the audit priors ledger is load-bearing"
else
    # The ledger also RECORDS removals, so a handful of the paths it names are
    # deliberately gone. Listing them is a two-way ratchet, the same mechanism as
    # tools/alloc_allowlist.txt: absent is expected, and a listed path that comes
    # BACK is a failure too, because then the entry describing its removal is
    # false. Do not use this to silence an anchor that merely moved — that is the
    # case the gate exists for.
    SETTLED_REMOVED="src/compute/gemv_ggml_compat.h src/compute/gemv_ggml_compat.cu
                     src/core/threading.h src/core/threading.cpp"
    ANCHORS=$(grep -ohE '\b(src|tests|tools|scripts|docs|include|cmake)/[A-Za-z0-9_./-]+\.[A-Za-z0-9]+\b' \
              docs/audit/SETTLED.md | sort -u || true)
    ANCHORBROKEN=0
    ANCHORN=0
    while IFS= read -r anchor; do
        [ -z "$anchor" ] && continue
        case " $(echo $SETTLED_REMOVED) " in
            *" $anchor "*)
                if [ -e "$anchor" ]; then
                    echo "  resurrected: $anchor is listed as removed in SETTLED.md but exists"
                    ANCHORBROKEN=$((ANCHORBROKEN+1))
                fi
                continue
                ;;
        esac
        ANCHORN=$((ANCHORN+1))
        if [ ! -e "$anchor" ]; then
            echo "  dead anchor: $anchor"
            ANCHORBROKEN=$((ANCHORBROKEN+1))
        fi
    done <<< "$ANCHORS"
    # Floor, because "0 anchors, all resolving" is a PASS that checked nothing —
    # the same shape as a --gtest_filter matching no tests and reporting PASSED,
    # or the `gpu` ctest label that is defined and never runs. The ledger had 49
    # anchors when this was written; 20 catches a gutted file without tripping on
    # ordinary edits.
    ANCHOR_FLOOR=20
    if [ "$ANCHORN" -lt "$ANCHOR_FLOOR" ]; then
        fail "only $ANCHORN anchors in docs/audit/SETTLED.md (expected >= $ANCHOR_FLOOR) — ledger gutted or the extraction broke"
    elif [ "$ANCHORBROKEN" -eq 0 ]; then
        pass "all $ANCHORN settled-prior anchors resolve"
    else
        fail "$ANCHORBROKEN dead anchor(s) in docs/audit/SETTLED.md"
    fi
fi

# ------------------------------------------------ 1d. finding-status coherence
# 1c checks that the FILES the ledger names still exist. It cannot check that
# the ledger's CLAIMS are still true, and that is the failure mode that has now
# hit three times, always in the same direction — a finding gets fixed and the
# ledger keeps listing it as open:
#   F-6  closed before SETTLED.md ever listed it as open (the file says so itself)
#   F-15 fixed in #1209; S-10 read "still open" for two days
#   F-10 fixed in #1227; section G read "Open: NOT settled" for a day
# A stale *open* entry is strictly worse than a stale closed one: it sends the
# next audit pass to work that is already done, which is the exact cost this
# ledger exists to prevent (eight of thirteen hypotheses in the 07-29 pass).
#
# The report is the authority on status: every finding there carries one status
# line. This cross-checks it against the ledger, both ways.
#   * every F-nn headline must carry a status mark  — no mark is how F-10, F-12
#     and F-24 sat statusless for a day, which is what let G go stale unnoticed
#   * ✅ / ⛔ mean resolved; ⚠️ means still open
#   * the set the report calls open must equal the set the ledger files under an
#     "Open" heading — a fixed finding left under "Open", or an open one missing
#     from the ledger entirely, both fail
#
# Note honestly: with 25/25 resolved the set comparison currently compares two
# empty sets. It is a ratchet for the next campaign, not a check that is doing
# work today. The per-finding status-mark check IS doing work today — it runs
# over all 25 — and the floor below is what stops the whole section degrading
# into a vacuous pass if the extraction ever silently stops matching.
#
# Known and deliberate: the ledger side collects EVERY F-nn mentioned under an
# "Open" heading, prose included, not just the entry headers. Mutation-testing
# this section surfaced it — renaming G back to "Open: NOT settled" reported
# eight findings because the section's preamble names F-6 and F-15 while
# explaining how they went stale. Tightening it to entry headers only would
# make the check miss a finding discussed but never given its own bullet, which
# is the likelier drift. A false positive here prints both sets and costs one
# read; a false negative costs the next audit pass a day.
#
# Mutation-validated 2026-08-05, all four fail as intended: strip a status mark
# (F-21) -> statusless; mark F-8 ⚠️ with no ledger entry -> sets disagree; rename
# G back to "Open: NOT settled" -> sets disagree; rename the F-nn headlines ->
# floor trips at 0.
section "finding-status coherence"
ARCH_REPORT=docs/audit/AUDIT_ARCH_2026_07_29.md
if [ ! -e "$ARCH_REPORT" ] || [ ! -e docs/audit/SETTLED.md ]; then
    fail "$ARCH_REPORT or docs/audit/SETTLED.md is missing — the audit ledger is load-bearing"
else
    STATUSLESS=""
    OPEN_IN_REPORT=""
    FINDINGN=0
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        id=$(echo "$line" | grep -oE '^\*\*F-[0-9]+' | tr -d '*' || true)
        [ -z "$id" ] && continue
        FINDINGN=$((FINDINGN+1))
        # Resolved marks win over the open mark: F-3 is "✅ RESOLVED … the
        # residual is ⛔ WON'T FIX", which carries both and is resolved.
        if echo "$line" | grep -q '✅\|⛔'; then
            :
        elif echo "$line" | grep -q '⚠️'; then
            OPEN_IN_REPORT="$OPEN_IN_REPORT $id"
        else
            STATUSLESS="$STATUSLESS $id"
        fi
    done <<< "$(grep -E '^\*\*F-[0-9]+ ' "$ARCH_REPORT" || true)"

    # Findings the ledger files under a heading that says "Open".
    OPEN_IN_LEDGER=$(awk '
        /^## / { open = (tolower($0) ~ /open/) }
        open && match($0, /F-[0-9]+/) { print substr($0, RSTART, RLENGTH) }
    ' docs/audit/SETTLED.md | sort -u | tr '\n' ' ')

    norm() { echo " $* " | tr ' ' '\n' | grep -v '^$' | sort -u | tr '\n' ' ' || true; }
    R_OPEN=$(norm "$OPEN_IN_REPORT")
    L_OPEN=$(norm "$OPEN_IN_LEDGER")

    FINDING_FLOOR=20
    if [ "$FINDINGN" -lt "$FINDING_FLOOR" ]; then
        fail "only $FINDINGN findings parsed from $ARCH_REPORT (expected >= $FINDING_FLOOR) — the extraction broke"
    elif [ -n "$STATUSLESS" ]; then
        fail "finding(s) with no status mark in $ARCH_REPORT:$STATUSLESS — add ✅ FIXED / ⚠️ open / ⛔ WON'T FIX"
    elif [ "$R_OPEN" != "$L_OPEN" ]; then
        echo "  report calls open: ${R_OPEN:-<none>}"
        echo "  ledger calls open: ${L_OPEN:-<none>}"
        fail "the report and docs/audit/SETTLED.md disagree on which findings are open"
    else
        pass "all $FINDINGN findings carry a status; report and ledger agree on ${R_OPEN:-none} open"
    fi
fi

# --------------------------------------------------------- 2. personal paths
# Flag real personal paths but allow the standard /home/user/ placeholder.
section "personal path leaks"
LEAKS=$(git ls-files \
        | grep -vE '^tests/fixtures/' \
        | xargs grep -lE '/home/[a-z]+/|/Users/[a-z]+/' 2>/dev/null \
        | xargs -r grep -lE '/home/(kekz|raph|raphael)/|/Users/(kekz|raph|raphael)/' 2>/dev/null || true)
if [ -z "$LEAKS" ]; then
    pass "no maintainer-username paths in tracked files"
else
    echo "$LEAKS" | sed 's/^/  /'
    fail "personal paths in tracked files"
fi

# ----------------------------------------------------------- 3. secret-shaped
section "credential-shaped strings"
SECRETS=$(git ls-files | xargs grep -lE 'sk-[A-Za-z0-9]{20,}|hf_[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}' 2>/dev/null || true)
if [ -z "$SECRETS" ]; then
    pass "no obviously-real API keys in tracked files"
else
    echo "$SECRETS" | sed 's/^/  /'
    fail "potential secrets in tracked files"
fi

# ------------------------------------------------- 4. tracked-but-ignorable
section "tracked binaries / build artefacts"
SUSPECTS=$(git ls-files | grep -E '\.(o|so|a|dylib|dll|fatbin|cubin|gguf|safetensors|bin|pt|onnx|nsys-rep|ncu-rep|sqlite|qdrep)$' || true)
if [ -z "$SUSPECTS" ]; then
    pass "no tracked build artefacts or model weights"
else
    echo "$SUSPECTS" | sed 's/^/  /'
    fail "tracked files match build/weight patterns"
fi

# ------------------------------------------------------- 5. license sanity
section "license"
if [ -f LICENSE ] && grep -q "MIT" LICENSE && grep -q "MIT" README.md; then
    pass "LICENSE present and README mentions MIT"
else
    fail "LICENSE missing or README license claim mismatched"
fi

# --------------------------------------------------- 5b. version consistency
# The version lives in three places that have to agree, and nothing pinned
# them: CMakeLists.txt is the source of truth, CHANGELOG.md must carry a
# released section for it, and docs/BENCHMARKS.md names the release its
# tabulated numbers were taken on. Bumping one and forgetting the others is a
# documented red flag in the shipping playbook — this makes it a failure.
section "version consistency"
CM_VER=$(sed -nE 's/^project\(imp .*VERSION ([0-9]+\.[0-9]+\.[0-9]+)\).*/\1/p' CMakeLists.txt | head -1)
CL_VER=$(grep -oE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' CHANGELOG.md | head -1 | tr -d '#[] ')
BM_VER=$(sed -nE 's/.*\*\*Toolchain \(current: `v([0-9]+\.[0-9]+\.[0-9]+)`\).*/\1/p' docs/BENCHMARKS.md | head -1)
if [ -z "$CM_VER" ]; then
    fail "no project(imp ... VERSION X.Y.Z) in CMakeLists.txt"
elif [ "$CM_VER" = "$CL_VER" ] && [ "$CM_VER" = "$BM_VER" ]; then
    pass "CMakeLists / CHANGELOG / BENCHMARKS all say $CM_VER"
else
    fail "version drift — CMakeLists '$CM_VER', CHANGELOG '${CL_VER:-none}', BENCHMARKS '${BM_VER:-none}'"
fi

# ------------------------------------------- 5b. changelog section hygiene
# Entries get prepended to [Unreleased] one PR at a time, and prepending a
# "### Changed" block in front of an existing one produces a section with the
# same heading twice. Keep-a-Changelog readers (and the release cut, which
# renames the whole block) then silently carry the duplicate into a tag.
# Mechanical, so gate it rather than rely on noticing.
section "changelog section hygiene"
UNREL=$(awk '/^## \[Unreleased\]/{f=1;next} /^## \[/{f=0} f' CHANGELOG.md)
# `|| true`: right after a release cut [Unreleased] is empty by design, grep
# then exits 1, and under `set -euo pipefail` that aborted the whole script —
# silently, with no FAIL line, before `make verify-fast` ever ran. v0.25.0 was
# cut with this check dying at exactly this point.
DUP=$(printf '%s\n' "$UNREL" | grep -E '^### ' | sort | uniq -d || true)
if [ -n "$DUP" ]; then
    printf '%s\n' "$DUP" | sed 's/^/  duplicate heading: /'
    fail "[Unreleased] repeats a '###' heading — merge the blocks"
else
    pass "[Unreleased] has no repeated '###' heading"
fi

# ----------------------------------------------- 6. defer to make verify-fast
section "make verify-fast"
if [ "${SKIP_VERIFY:-0}" = "1" ]; then
    echo "  (skipped via SKIP_VERIFY=1)"
else
    # A release runs every gate, whatever the shell exported: the pre-push hook
    # sets IMP_VERIFY_SKIP_PERF=1 for diffs outside the measured paths.
    MODEL_STAGES_RUN=$((MODEL_STAGES_RUN+1))
    if IMP_VERIFY_SKIP_PERF=0 IMP_VERIFY_SKIP_VRAM=0 IMP_VERIFY_SKIP_GRAPHS=0 \
       make verify-fast >/tmp/imp_check_release_verify.log 2>&1; then
        pass "make verify-fast"
    else
        echo "  log: /tmp/imp_check_release_verify.log"
        tail -30 /tmp/imp_check_release_verify.log | sed 's/^/  /'
        fail "make verify-fast"
    fi
fi

# ----------------------------------------------- 7. defer to make test-server
# The HTTP surface, which verify-fast never touches. Its batteries are the only
# thing in this repository that drives handlers.cpp and batching_engine against
# a live model, so a release that skips it ships whatever the wire protocol has
# broken since the last manual run.
section "make test-server"
if [ "${SKIP_VERIFY:-0}" = "1" ]; then
    echo "  (skipped via SKIP_VERIFY=1)"
else
    MODEL_STAGES_RUN=$((MODEL_STAGES_RUN+1))
    if make test-server >/tmp/imp_check_release_server.log 2>&1; then
        pass "make test-server"
    else
        echo "  log: /tmp/imp_check_release_server.log"
        # The per-battery verdicts are what names the culprit; the tail alone is
        # usually the make error and says nothing.
        grep -E '^   -> |^test-server:' /tmp/imp_check_release_server.log | sed 's/^/  /' || true
        fail "make test-server"
    fi
fi

# --------------------------------------------------------------------- end
echo
if [ "$FAIL" -eq 0 ] && [ "$MODEL_STAGES_RUN" -eq 0 ]; then
    # Exit 0 on purpose — see the header. The wording is the gate here: nobody
    # should be able to read this line as a release verdict.
    echo "${YLW}check-release: cheap checks passed — NOT a release verdict${RST}"
    echo "         SKIP_VERIFY=1 skipped verify-fast and test-server, so no model ran."
    echo "         Re-run without it before tagging."
    exit 0
fi
if [ "$FAIL" -eq 0 ]; then
    echo "${GRN}check-release: all gates passed${RST}"
    exit 0
else
    echo "${RED}check-release: $FAIL gate(s) failed${RST}"
    exit 1
fi
