#!/usr/bin/env bash
# Pre-release sanity gate: doc-link/secret/tracked-binary checks, then defers to make
# verify-fast (tests+perf+smoke), make test-server (HTTP surface), make test-spec-fidelity
# (captured verify chunk), make bench-competitive (vs a competitor, GOAL.md release bar 2).
# SKIP_VERIFY=1 skips all four; the summary then reports what actually ran instead of "all
# gates passed" (the Release hygiene CI job runs this way, no GPU there). Exit 0 always: the
# summary line, not the exit code, is what a human reads before tagging.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

RED=$(tput setaf 1 || echo)
GRN=$(tput setaf 2 || echo)
YLW=$(tput setaf 3 || echo)
RST=$(tput sgr0 || echo)

FAIL=0
# Model-backed stages that actually put a checkpoint in front of the GPU.
# SKIP_VERIFY=1 leaves this at zero, and the summary refuses to report success
# while it is — see the header.
MODEL_STAGES_RUN=0
section() { echo; echo "${YLW}== $* ==${RST}"; }
pass()    { echo "${GRN}PASS${RST} $*"; }
fail()    { echo "${RED}FAIL${RST} $*"; FAIL=$((FAIL+1)); }

# ---------------------------------------------------------------- 1. doc links
# Every (./*.md or docs/*.md) link of the form ](path) — where path looks
# like a relative file — must resolve to a tracked file.
section "doc links"
# Resolve each markdown link against the file that CONTAINS it (the only correct answer);
# do not dedupe targets globally and guess a prefix from a fixed list.
BROKEN=0
while IFS= read -r docfile; do
    [ -z "$docfile" ] && continue
    dir=$(dirname "$docfile")
    while IFS= read -r link; do
        [ -z "$link" ] && continue
        case "$link" in http*|https*|mailto:*) continue ;; esac
        [ -e "$dir/$link" ] || { echo "  broken: $docfile -> $link"; BROKEN=$((BROKEN+1)); }
    done < <(grep -Eho '\]\(([^)# ]+\.(md|example|json|sh|cmake|h|cpp|cu))\)' "$docfile" 2>/dev/null \
             | sed -E 's/^\]\(//; s/\)$//' | sort -u)
done < <(git ls-files -- 'README.md' 'CONTRIBUTING.md' 'CHANGELOG.md' 'docs/**/*.md' 'docs/*.md')
[ "$BROKEN" -eq 0 ] && pass "all internal doc links resolve" \
                   || fail "$BROKEN broken internal doc link(s)"

# A "see docs/<name>.md" pointer in a comment or script is a promise the file exists;
# checked separately from markdown links. Allowlisted: paths a tool WRITES rather than reads.
section "doc pointers in code"
DOC_ALLOW="docs/gemma4_layer_diff.md"   # generated by tools/analysis/layer_diff.py --out-md
DOCREFS=$(git ls-files -- '*.sh' '*.py' '*.cpp' '*.cu' '*.h' '*.hpp' '*.toml' '*.cmake' 'CMakeLists.txt' \
          | xargs grep -ahoE 'https?://[^[:space:])]*|\bdocs/[A-Za-z0-9_./-]+\.md\b' 2>/dev/null \
          | grep -v '://' | sort -u || true)
DOCBROKEN=0
while IFS= read -r ref; do
    [ -z "$ref" ] && continue
    case " $DOC_ALLOW " in *" $ref "*) continue ;; esac
    if [ ! -e "$ref" ]; then
        echo "  dead pointer: $ref"
        DOCBROKEN=$((DOCBROKEN+1))
    fi
done <<< "$DOCREFS"

# Covers bare names (e.g. TEST_AUDIT) and paths outside the docs/ prefix, resolved by BASENAME
# so a doc that only moved still passes. The docs/ scan above stays strict on the full path.
BARE_ALLOW="MODEL_VALIDATION_REPORT.md"   # written by scripts/validate_safetensors.py, not read
# Named in comments but living in the agent memory store (outside this repo), so
# no repo gate can resolve them. Listed rather than deleted: they are the
# provenance for why the code around them looks the way it does.
BARE_ALLOW="$BARE_ALLOW dead_ends.md fp4_pv_potential_2026_04_25.md"
BARE_ALLOW="$BARE_ALLOW llm_compressor_input_scale_dead_end_2026_05_07.md"
BARE_ALLOW="$BARE_ALLOW prefill_graph_blockers_2026_05_14.md"
BARE_ALLOW="$BARE_ALLOW qwen35_27b_mxfp4_ima_2026_04_25.md"
BARE_ALLOW="$BARE_ALLOW spec_decode_qwen36_broken_2026_05_02.md"
BARE_ALLOW="$BARE_ALLOW bench_sustained_load_cublas_algo_drift_2026_05_23.md"
BARE_ALLOW="$BARE_ALLOW gemma4_working_2026_04_14.md"
BARE_ALLOW="$BARE_ALLOW nvfp4_long_context_regression_2026_04_28.md"
BARE_ALLOW="$BARE_ALLOW sass_audit_120a_no_tcgen05_2026_05_04.md"
TRACKED_BASENAMES=$(git ls-files | sed 's#.*/##' | sort -u)
# A URL is matched as an alternative in the same grep pass, then dropped: filtering the
# extracted token separately fails because a URL's token has no scheme and reads as a dead file.
# Per-file grep, not a sed-merged stream: test_sse_stream_utils.cpp is binary and would
# silence the whole scan under -a.
BAREREFS=$(git ls-files -- '*.sh' '*.py' '*.cpp' '*.cu' '*.h' '*.hpp' '*.toml' '*.cmake' 'CMakeLists.txt' \
           | xargs grep -ahoE 'https?://[^[:space:])]*|[A-Za-z0-9_./-]+\.md\b' 2>/dev/null \
           | grep -v '://' \
           | grep -v '^docs/' | sed 's#.*/##' | sort -u || true)
BARECHECKED=0
while IFS= read -r ref; do
    [ -z "$ref" ] && continue
    case " $BARE_ALLOW " in *" $ref "*) continue ;; esac
    BARECHECKED=$((BARECHECKED+1))
    # Herestring, not `printf ... | grep -q`: grep -q exits at the first match, printf then dies
    # of EPIPE, and set -o pipefail turns that into a false failure even though grep found the name.
    # It is a race: fires only when the match comes early in the sorted list.
    if ! grep -qxF "$ref" <<< "$TRACKED_BASENAMES"; then
        echo "  dead pointer: $ref (no tracked file has this name)"
        DOCBROKEN=$((DOCBROKEN+1))
    fi
done <<< "$BAREREFS"
# Floor for the same reason 1c has one: "0 names, all resolving" is a pass that
# checked nothing. There were 33 distinct bare names when this was written.
if [ "$BARECHECKED" -lt 10 ]; then
    fail "bare-*.md scan checked only $BARECHECKED name(s) — the corpus or the pattern broke"
fi
[ "$DOCBROKEN" -eq 0 ] && pass "every docs/*.md path and bare *.md name in code resolves ($BARECHECKED bare names checked)" \
                      || fail "$DOCBROKEN dead doc pointer(s) in code"

# docs/audit/SETTLED.md is the ledger an audit reads before generating hypotheses; each entry
# names the file that makes it settled. A dead anchor means the entry is a stale prior, not a
# true statement about the engine. Same shape as 1b, different corpus.
section "settled-prior anchors"
if [ ! -e docs/audit/SETTLED.md ]; then
    fail "docs/audit/SETTLED.md is missing — the audit priors ledger is load-bearing"
else
    # The ledger also records deliberate removals (two-way ratchet, same as tools/alloc_allowlist.txt):
    # absent is expected, and a listed path coming BACK is also a failure.
    # Not for anchors that merely moved; that's what the gate above catches.
    SETTLED_REMOVED="src/compute/gemv_ggml_compat.h src/compute/gemv_ggml_compat.cu
                     src/core/threading.h src/core/threading.cpp"
    ANCHORS=$(grep -ohE '\b(src|tests|tools|scripts|docs|include|cmake)/[A-Za-z0-9_./-]+\.[A-Za-z0-9]+\b' \
              docs/audit/SETTLED.md | sort -u || true)
    ANCHORBROKEN=0
    ANCHORN=0
    while IFS= read -r anchor; do
        [ -z "$anchor" ] && continue
        case " $(echo $SETTLED_REMOVED) " in
            *" $anchor "*)
                if [ -e "$anchor" ]; then
                    echo "  resurrected: $anchor is listed as removed in SETTLED.md but exists"
                    ANCHORBROKEN=$((ANCHORBROKEN+1))
                fi
                continue
                ;;
        esac
        ANCHORN=$((ANCHORN+1))
        if [ ! -e "$anchor" ]; then
            echo "  dead anchor: $anchor"
            ANCHORBROKEN=$((ANCHORBROKEN+1))
        fi
    done <<< "$ANCHORS"
    # Floor guards "0 anchors, all resolving" passing vacuously (same shape as an empty gtest_filter
    # reporting PASSED). Ledger had 49 anchors when written; 20 catches a gutted file without
    # tripping on ordinary edits.
    ANCHOR_FLOOR=20
    if [ "$ANCHORN" -lt "$ANCHOR_FLOOR" ]; then
        fail "only $ANCHORN anchors in docs/audit/SETTLED.md (expected >= $ANCHOR_FLOOR) — ledger gutted or the extraction broke"
    elif [ "$ANCHORBROKEN" -eq 0 ]; then
        pass "all $ANCHORN settled-prior anchors resolve"
    else
        fail "$ANCHORBROKEN dead anchor(s) in docs/audit/SETTLED.md"
    fi
fi

# Cross-checks the audit report's finding-status marks against SETTLED.md's Open-heading set,
# both directions: every F-nn headline must carry a status mark (checkmark/x resolved, warning
# open), and the report's open set must equal the ledger's.
# A stale OPEN entry is worse than stale closed: it sends the next audit to redo finished work.
# Set-comparison is a ratchet (currently all resolved = two empty sets); the per-finding
# status-mark check runs over every finding and does real work today.
section "finding-status coherence"
ARCH_REPORT=docs/audit/AUDIT_ARCH_2026_07_29.md
if [ ! -e "$ARCH_REPORT" ] || [ ! -e docs/audit/SETTLED.md ]; then
    fail "$ARCH_REPORT or docs/audit/SETTLED.md is missing — the audit ledger is load-bearing"
else
    STATUSLESS=""
    OPEN_IN_REPORT=""
    FINDINGN=0
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        id=$(echo "$line" | grep -oE '^\*\*F-[0-9]+' | tr -d '*' || true)
        [ -z "$id" ] && continue
        FINDINGN=$((FINDINGN+1))
        # Resolved marks win over the open mark: F-3 is "✅ RESOLVED … the
        # residual is ⛔ WON'T FIX", which carries both and is resolved.
        if grep -q '✅\|⛔' <<< "$line"; then
            :
        elif grep -q '⚠️' <<< "$line"; then
            OPEN_IN_REPORT="$OPEN_IN_REPORT $id"
        else
            STATUSLESS="$STATUSLESS $id"
        fi
    done <<< "$(grep -E '^\*\*F-[0-9]+ ' "$ARCH_REPORT" || true)"

    # Findings the ledger files under a heading that says "Open".
    OPEN_IN_LEDGER=$(awk '
        /^## / { open = (tolower($0) ~ /open/) }
        open && match($0, /F-[0-9]+/) { print substr($0, RSTART, RLENGTH) }
    ' docs/audit/SETTLED.md | sort -u | tr '\n' ' ')

    norm() { echo " $* " | tr ' ' '\n' | grep -v '^$' | sort -u | tr '\n' ' ' || true; }
    R_OPEN=$(norm "$OPEN_IN_REPORT")
    L_OPEN=$(norm "$OPEN_IN_LEDGER")

    FINDING_FLOOR=20
    if [ "$FINDINGN" -lt "$FINDING_FLOOR" ]; then
        fail "only $FINDINGN findings parsed from $ARCH_REPORT (expected >= $FINDING_FLOOR) — the extraction broke"
    elif [ -n "$STATUSLESS" ]; then
        fail "finding(s) with no status mark in $ARCH_REPORT:$STATUSLESS — add ✅ FIXED / ⚠️ open / ⛔ WON'T FIX"
    elif [ "$R_OPEN" != "$L_OPEN" ]; then
        echo "  report calls open: ${R_OPEN:-<none>}"
        echo "  ledger calls open: ${L_OPEN:-<none>}"
        fail "the report and docs/audit/SETTLED.md disagree on which findings are open"
    else
        pass "all $FINDINGN findings carry a status; report and ledger agree on ${R_OPEN:-none} open"
    fi
fi

# --------------------------------------------------------- 2. personal paths
# Flag real personal paths but allow the standard /home/user/ placeholder.
section "personal path leaks"
LEAKS=$(git ls-files \
        | grep -vE '^tests/fixtures/' \
        | xargs grep -lE '/home/[a-z]+/|/Users/[a-z]+/' 2>/dev/null \
        | xargs -r grep -lE '/home/(kekz|raph|raphael)/|/Users/(kekz|raph|raphael)/' 2>/dev/null || true)
if [ -z "$LEAKS" ]; then
    pass "no maintainer-username paths in tracked files"
else
    echo "$LEAKS" | sed 's/^/  /'
    fail "personal paths in tracked files"
fi

# ----------------------------------------------------------- 3. secret-shaped
section "credential-shaped strings"
SECRETS=$(git ls-files | xargs grep -lE 'sk-[A-Za-z0-9]{20,}|hf_[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}' 2>/dev/null || true)
if [ -z "$SECRETS" ]; then
    pass "no obviously-real API keys in tracked files"
else
    echo "$SECRETS" | sed 's/^/  /'
    fail "potential secrets in tracked files"
fi

# ------------------------------------------------- 4. tracked-but-ignorable
section "tracked binaries / build artefacts"
SUSPECTS=$(git ls-files | grep -E '\.(o|so|a|dylib|dll|fatbin|cubin|gguf|safetensors|bin|pt|onnx|nsys-rep|ncu-rep|sqlite|qdrep)$' || true)
if [ -z "$SUSPECTS" ]; then
    pass "no tracked build artefacts or model weights"
else
    echo "$SUSPECTS" | sed 's/^/  /'
    fail "tracked files match build/weight patterns"
fi

# ------------------------------------------------------- 5. license sanity
section "license"
if [ -f LICENSE ] && grep -q "MIT" LICENSE && grep -q "MIT" README.md; then
    pass "LICENSE present and README mentions MIT"
else
    fail "LICENSE missing or README license claim mismatched"
fi
# nvfp4_quant_hw.cu (Apache-2.0, adapted from SageAttention) requires its license text in
# every distribution (AUDIT_arch_2026 H-7). Four-way pin: file, content, OCI label, README pointer.
if [ -f THIRD_PARTY_LICENSES.md ] && grep -q "Apache License" THIRD_PARTY_LICENSES.md \
   && grep -q "SageAttention" THIRD_PARTY_LICENSES.md \
   && grep -q 'image.licenses="MIT AND Apache-2.0"' Dockerfile \
   && grep -q "THIRD_PARTY_LICENSES.md" Dockerfile \
   && grep -q "THIRD_PARTY_LICENSES.md" README.md; then
    pass "THIRD_PARTY_LICENSES.md carries the Apache-2.0 text; Dockerfile label + COPY and README point at it"
else
    fail "THIRD_PARTY_LICENSES.md missing or incomplete, or the Dockerfile label / COPY / README pointer do not name it"
fi

# Version must agree in three places: CMakeLists.txt (source of truth), CHANGELOG.md (a
# released section for it), docs/BENCHMARKS.md (the release its tabulated numbers were taken on).
section "version consistency"
CM_VER=$(sed -nE 's/^project\(imp .*VERSION ([0-9]+\.[0-9]+\.[0-9]+)\).*/\1/p' CMakeLists.txt | head -1)
CL_VER=$(grep -oE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' CHANGELOG.md | head -1 | tr -d '#[] ')
BM_VER=$(sed -nE 's/.*\*\*Toolchain \(current: `v([0-9]+\.[0-9]+\.[0-9]+)`\).*/\1/p' docs/BENCHMARKS.md | head -1)
if [ -z "$CM_VER" ]; then
    fail "no project(imp ... VERSION X.Y.Z) in CMakeLists.txt"
elif [ "$CM_VER" = "$CL_VER" ] && [ "$CM_VER" = "$BM_VER" ]; then
    pass "CMakeLists / CHANGELOG / BENCHMARKS all say $CM_VER"
else
    fail "version drift — CMakeLists '$CM_VER', CHANGELOG '${CL_VER:-none}', BENCHMARKS '${BM_VER:-none}'"
fi

# Covers every living doc (roadmap.md, docs/*.md, docs/internals/*.md, root docs); archive/,
# plans/, audit/ excluded (their line numbers describe the commit they document).
# Gates a file:line citation past EOF and a renamed bare docs/*.md name. Same gate runs in the
# pre-commit/pre-push hooks and the Build job (citations selection).
section "roadmap citations"
if python3 scripts/check_doc_citations.py . >/tmp/imp_check_citations.log 2>&1; then
    pass "living-doc citations resolve"
else
    sed 's/^/  /' /tmp/imp_check_citations.log
    fail "a living doc cites files or lines that no longer exist"
fi

# Entries prepend to [Unreleased] one PR at a time; prepending a duplicate "### Changed"
# heading produces two sections with the same name, silently carried into the release tag.
section "changelog section hygiene"
UNREL=$(awk '/^## \[Unreleased\]/{f=1;next} /^## \[/{f=0} f' CHANGELOG.md)
# `|| true`: right after a release cut [Unreleased] is empty, grep exits 1, and
# set -euo pipefail would abort the script silently before make verify-fast ever ran.
DUP=$(printf '%s\n' "$UNREL" | grep -E '^### ' | sort | uniq -d || true)
if [ -n "$DUP" ]; then
    printf '%s\n' "$DUP" | sed 's/^/  duplicate heading: /'
    fail "[Unreleased] repeats a '###' heading — merge the blocks"
else
    pass "[Unreleased] has no repeated '###' heading"
fi

# ----------------------------------------------- 6. defer to make verify-fast
section "make verify-fast"
if [ "${SKIP_VERIFY:-0}" = "1" ]; then
    echo "  (skipped via SKIP_VERIFY=1)"
else
    # A release runs every gate, whatever the shell exported: the pre-push hook
    # sets IMP_VERIFY_SKIP_PERF=1 for diffs outside the measured paths.
    MODEL_STAGES_RUN=$((MODEL_STAGES_RUN+1))
    if IMP_VERIFY_SKIP_PERF=0 IMP_VERIFY_SKIP_VRAM=0 IMP_VERIFY_SKIP_GRAPHS=0 \
       make verify-fast >/tmp/imp_check_release_verify.log 2>&1; then
        pass "make verify-fast"
    else
        echo "  log: /tmp/imp_check_release_verify.log"
        tail -30 /tmp/imp_check_release_verify.log | sed 's/^/  /'
        fail "make verify-fast"
    fi
fi

# The HTTP surface, untouched by verify-fast: the only battery driving handlers.cpp and
# batching_engine against a live model end to end.
section "make test-server"
if [ "${SKIP_VERIFY:-0}" = "1" ]; then
    echo "  (skipped via SKIP_VERIFY=1)"
else
    MODEL_STAGES_RUN=$((MODEL_STAGES_RUN+1))
    if make test-server >/tmp/imp_check_release_server.log 2>&1; then
        pass "make test-server"
    else
        echo "  log: /tmp/imp_check_release_server.log"
        # The per-battery verdicts are what names the culprit; the tail alone is
        # usually the make error and says nothing.
        grep -E '^   -> |^test-server:' /tmp/imp_check_release_server.log | sed 's/^/  /' || true
        fail "make test-server"
    fi
fi

# The captured speculative verify chunk, untouched by the two stages above. Runs in its own
# container (Makefile test-spec-fidelity): checkpoint + comparison forward don't fit behind
# another model, so the case skips silently in a batched lane without its own stage here.
section "make test-spec-fidelity"
if [ "${SKIP_VERIFY:-0}" = "1" ]; then
    echo "  (skipped via SKIP_VERIFY=1)"
else
    MODEL_STAGES_RUN=$((MODEL_STAGES_RUN+1))
    if make test-spec-fidelity >/tmp/imp_check_release_specfid.log 2>&1; then
        # A skip here is not a pass: the case gates itself on free VRAM, and a
        # busy card would turn this stage into a green line that checked nothing.
        if grep -q '\[  SKIPPED \]' /tmp/imp_check_release_specfid.log; then
            echo "  log: /tmp/imp_check_release_specfid.log"
            grep -A1 'Skipped' /tmp/imp_check_release_specfid.log | sed 's/^/  /' | head -4 || true
            fail "make test-spec-fidelity (skipped — the card was not free enough to run it)"
        else
            pass "make test-spec-fidelity"
        fi
    else
        echo "  log: /tmp/imp_check_release_specfid.log"
        grep -E 'cached-graph replays|too few to judge' /tmp/imp_check_release_specfid.log |
            sed 's/^/  /' || true
        fail "make test-spec-fidelity"
    fi
fi

# GOAL.md release bar 2: decode must lead llama.cpp by >=5% on every hero. Competitor image
# pinned by digest in scripts/bench_competitive.sh, so this can't silently drift onto a newer build.
section "make bench-competitive (release bar 2)"
if [ "${SKIP_VERIFY:-0}" = "1" ]; then
    echo "  (skipped via SKIP_VERIFY=1)"
else
    MODEL_STAGES_RUN=$((MODEL_STAGES_RUN+1))
    if RELEASE_BAR=1 make bench-competitive >/tmp/imp_check_release_bench.log 2>&1; then
        # Surface the scope, not just the verdict. A bare green line here would
        # be read as "the seven-hero blocker is satisfied" by anyone who does
        # not open the script, and two of the seven cannot be contested at all.
        sed -n '/cannot contest/,/^$/p' /tmp/imp_check_release_bench.log | sed 's/^/  /' || true
        grep -A2 '^RELEASE BAR:' /tmp/imp_check_release_bench.log | sed 's/^/  /' || true
        pass "make bench-competitive (release bar 2)"
    else
        echo "  log: /tmp/imp_check_release_bench.log"
        grep -E 'FAIL: release bar|not measured|absent from|bar ' /tmp/imp_check_release_bench.log |
            sed 's/^/  /' || true
        fail "make bench-competitive (release bar 2)"
    fi
fi

# --------------------------------------------------------------------- end
echo
if [ "$FAIL" -eq 0 ] && [ "$MODEL_STAGES_RUN" -eq 0 ]; then
    # Exit 0 on purpose — see the header. The wording is the gate here: nobody
    # should be able to read this line as a release verdict.
    echo "${YLW}check-release: cheap checks passed — NOT a release verdict${RST}"
    echo "         SKIP_VERIFY=1 skipped verify-fast, test-server, test-spec-fidelity"
    echo "         and bench-competitive,"
    echo "         so no model ran."
    echo "         Re-run without it before tagging."
    exit 0
fi
if [ "$FAIL" -eq 0 ]; then
    echo "${GRN}check-release: all gates passed${RST}"
    exit 0
else
    echo "${RED}check-release: $FAIL gate(s) failed${RST}"
    exit 1
fi
