#!/usr/bin/env python3
"""I1 gate: exactly one module talks to the CUDA driver about memory.

docs/MEMORY_ARCHITECTURE.md invariant I1 — no cudaMalloc / cudaMallocAsync /
cudaFree / cuMemCreate / thrust::device_vector / pinned-host allocation outside
src/memory/. Everything else receives typed views.

The engine cannot get there in one commit, so the gate runs against an explicit
allowlist that shrinks monotonically. Two hard failures:

  1. A file allocates and is NOT on the allowlist  -> the invariant regressed.
  2. A file IS on the allowlist but no longer allocates -> the entry is stale
     and must be deleted. This is what makes "the allowlist shrinks
     monotonically" true by construction rather than by good intentions: you
     cannot migrate a file and leave its entry behind, so the list is always an
     accurate picture of the remaining debt.

Scope is src/ — the engine. tools/imp-bench, tools/standalone and tools/analysis
are separate probe binaries that legitimately allocate directly; they are not
part of the engine's memory subsystem and are not gated.

Usage:
    python3 tools/check_alloc_sites.py            # check (CI)
    python3 tools/check_alloc_sites.py --update   # rewrite the allowlist
    python3 tools/check_alloc_sites.py --stats    # progress only, never fails
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / "src"
ALLOWLIST = REPO / "tools" / "alloc_allowlist.txt"

# The module that IS allowed to do this.
EXEMPT_PREFIXES = ("src/memory/",)

SUFFIXES = (".cpp", ".cu", ".h", ".cuh", ".hpp")

# Driver/runtime memory APIs. Ordered longest-first so the alternation reports
# the most specific name (cudaMallocAsync, not cudaMalloc).
APIS = [
    "cudaMallocAsync",
    "cudaMallocManaged",
    "cudaMallocPitch",
    "cudaMallocHost",
    "cudaMalloc3D",
    "cudaMalloc",
    "cudaFreeAsync",
    "cudaFreeHost",
    "cudaFree",
    "cudaHostAlloc",
    "cudaHostRegister",
    "cudaHostUnregister",
    "cuMemAddressReserve",
    "cuMemAddressFree",
    "cuMemCreate",
    "cuMemRelease",
    "cuMemMap",
    "cuMemUnmap",
    "cuMemSetAccess",
    "thrust::device_vector",
]
# Word-boundary on the left so `imp_cudaMalloc_wrapper` is not a false hit, and
# a '(' or '<' on the right so a mention in an identifier is not either.
PATTERN = re.compile(r"\b(" + "|".join(re.escape(a) for a in APIS) + r")\s*[(<]")

# A line whose first non-space run starts a comment. Cheap and good enough:
# the alternative is a real preprocessor, and a banned call hidden inside a
# block comment that starts mid-line is not a failure mode worth handling.
COMMENT_LINE = re.compile(r"^\s*(//|\*|/\*)")


def scan() -> dict[str, list[tuple[int, str]]]:
    """rel_path -> [(line_no, api)] for every non-exempt file that allocates."""
    hits: dict[str, list[tuple[int, str]]] = {}
    for path in sorted(SRC.rglob("*")):
        if path.suffix not in SUFFIXES or not path.is_file():
            continue
        rel = path.relative_to(REPO).as_posix()
        if rel.startswith(EXEMPT_PREFIXES):
            continue
        found: list[tuple[int, str]] = []
        with path.open(encoding="utf-8", errors="replace") as fh:
            for n, line in enumerate(fh, 1):
                if COMMENT_LINE.match(line):
                    continue
                m = PATTERN.search(line)
                if m:
                    found.append((n, m.group(1)))
        if found:
            hits[rel] = found
    return hits


def read_allowlist() -> list[str]:
    if not ALLOWLIST.exists():
        return []
    out = []
    for line in ALLOWLIST.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            out.append(line)
    return out


def write_allowlist(files: dict[str, list[tuple[int, str]]]) -> None:
    total = sum(len(v) for v in files.values())
    body = [
        "# I1 allowlist — files outside src/memory/ that still call the CUDA",
        "# driver about memory directly. Generated by tools/check_alloc_sites.py.",
        "#",
        "# THIS LIST ONLY SHRINKS. Adding an entry is a deliberate act that has to",
        "# be justified in review; the gate fails on any file that allocates and is",
        "# not listed, and equally on any listed file that no longer allocates.",
        "#",
        f"# remaining: {len(files)} files, {total} sites",
        "",
    ]
    for rel in sorted(files):
        body.append(f"{rel}  # {len(files[rel])}")
    ALLOWLIST.write_text("\n".join(body) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--update", action="store_true", help="rewrite the allowlist from the tree")
    ap.add_argument("--stats", action="store_true", help="print progress, never fail")
    args = ap.parse_args()

    hits = scan()
    total_sites = sum(len(v) for v in hits.values())

    if args.update:
        write_allowlist(hits)
        print(f"allowlist updated: {len(hits)} files, {total_sites} sites")
        return 0

    allowed = set(read_allowlist())
    offenders = sorted(set(hits) - allowed)
    stale = sorted(allowed - set(hits))

    print(f"I1: {len(hits)} files / {total_sites} sites outside src/memory/ "
          f"(allowlist: {len(allowed)} files)")

    if args.stats:
        for rel in sorted(hits, key=lambda r: -len(hits[r]))[:15]:
            print(f"  {len(hits[rel]):4d}  {rel}")
        return 0

    rc = 0
    if offenders:
        rc = 1
        print("\nFAIL: these files allocate but are not on the I1 allowlist.")
        print("Route them through src/memory/ (docs/MEMORY_ARCHITECTURE.md A3),")
        print("or, if that is genuinely not possible yet, justify the addition in review.")
        for rel in offenders:
            for line_no, api in hits[rel][:5]:
                print(f"  {rel}:{line_no}: {api}")
            if len(hits[rel]) > 5:
                print(f"  {rel}: ... and {len(hits[rel]) - 5} more")

    if stale:
        rc = 1
        print("\nFAIL: these allowlist entries no longer allocate — delete them.")
        print("(The list must stay an accurate picture of the remaining debt.)")
        for rel in stale:
            print(f"  {rel}")

    if rc == 0:
        print("OK — no new direct allocation sites.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
