#!/usr/bin/env python3
"""Generate the tokenizer's Unicode tables from the running Python's unicodedata:
  src/model/unicode_class.cpp     class bits per codepoint (regex pre-tokenizers, NFC quick check)
  src/model/unicode_nfc_data.cpp  canonical decompositions + combining classes (NFC)

  docker run --rm --user $(id -u):$(id -g) -v $PWD:/w -w /w python:3.12-slim \
      python tools/gen_unicode_tables.py
"""
import unicodedata as ud

VER = ud.unidata_version

# White_Space property (PropList.txt); unicodedata does not expose it.
WHITE_SPACE = {*range(0x09, 0x0E), 0x20, 0x85, 0xA0, 0x1680, *range(0x2000, 0x200B),
               0x2028, 0x2029, 0x202F, 0x205F, 0x3000}


def canon_decomp(cp):
    d = ud.decomposition(chr(cp))
    if not d or d.startswith("<"):
        return None
    return [int(p, 16) for p in d.split()]


# Primary composites: 2-codepoint canonical decompositions that NFC recomposes.
DECOMP = {}
PRIMARY = set()
SECOND = set()
for cp in range(0x110000):
    d = canon_decomp(cp)
    if d is None:
        continue
    DECOMP[cp] = d
    if len(d) == 2 and ud.normalize("NFC", chr(d[0]) + chr(d[1])) == chr(cp):
        PRIMARY.add(cp)
        SECOND.add(d[1])


def nfc_unstable(cp):
    ch = chr(cp)
    return ud.combining(ch) != 0 or cp in SECOND or ud.normalize("NFC", ch) != ch or \
        0x1100 <= cp <= 0x11FF  # conjoining jamo (algorithmic Hangul composition)


def bits(cp):
    cat = ud.category(chr(cp))
    b = 0
    if cat in ("Lu", "Lt"):
        b |= 1  # kUpper
    if cat == "Ll":
        b |= 2  # kLower
    if cat in ("Lm", "Lo"):
        b |= 4  # kOtherLetter
    if cat[0] == "M":
        b |= 8  # kMark
    if cat[0] == "N":
        b |= 16  # kNumber
    if cp in WHITE_SPACE:
        b |= 32  # kSpace
    if nfc_unstable(cp):
        b |= 64  # kNfcUnstable
    return b


def runs(fn):
    out, prev = [], None
    for cp in range(0x110000):
        v = fn(cp)
        if v != prev:
            out.append((cp << 8) | v)
            prev = v
    return out


def rows(values, per_line, width=8, suffix="u"):
    return "\n".join("    " + ", ".join(f"0x{v:0{width}x}{suffix}" for v in values[i:i + per_line]) + ","
                     for i in range(0, len(values), per_line))


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


HEADER = f"""// GENERATED by tools/gen_unicode_tables.py (Unicode {VER}). Do not edit.
#include "model/unicode_class.h"

#include <algorithm>
#include <cstdint>
#include <iterator>

namespace imp::unicode {{

namespace {{
"""

RUN_LOOKUP = """
uint8_t {fn}(uint32_t cp) {{
    if (cp > 0x10FFFF)
        return 0;
    const uint32_t* it = std::upper_bound(std::begin({table}), std::end({table}), (cp << 8) | 0xFFu);
    return static_cast<uint8_t>(*(it - 1) & 0xFFu);
}}
"""


def gen_class():
    r = runs(bits)
    ccc = runs(lambda cp: ud.combining(chr(cp)))
    write("src/model/unicode_class.cpp", HEADER + f"""
// (first codepoint << 8) | class bits, one entry per run of equal bits.
constexpr uint32_t kRuns[] = {{
{rows(r, 8)}
}};

// (first codepoint << 8) | canonical combining class, one entry per run.
constexpr uint32_t kCccRuns[] = {{
{rows(ccc, 8)}
}};

}}  // namespace
""" + RUN_LOOKUP.format(fn="cp_class", table="kRuns") + RUN_LOOKUP.format(fn="combining_class", table="kCccRuns")
          + "\n}  // namespace imp::unicode\n")
    return len(r), len(ccc)


def gen_nfc():
    # cp << 43 | first << 22 | second << 1 | primary; second 0 = singleton.
    packed = []
    for cp in sorted(DECOMP):
        d = DECOMP[cp]
        second = d[1] if len(d) == 2 else 0
        packed.append((cp << 43) | (d[0] << 22) | (second << 1) | (1 if cp in PRIMARY else 0))
    write("src/model/unicode_nfc_data.cpp", HEADER + f"""
// Canonical decompositions sorted by codepoint, packed as in decomposition_table().
constexpr uint64_t kDecomp[] = {{
{rows(packed, 4, 16, "ull")}
}};

}}  // namespace

std::span<const uint64_t> decomposition_table() {{ return kDecomp; }}

}}  // namespace imp::unicode
""")
    return len(DECOMP), len(PRIMARY)


if __name__ == "__main__":
    n, c = gen_class()
    d, p = gen_nfc()
    print(f"Unicode {VER}: {n} class runs, {c} ccc runs, {d} decompositions ({p} primary composites)")
